"""
texts.py
========
Каталог всего, что видит пользователь бота: фразы, подписи кнопок и полей,
цвета, thumbnails. Здесь — значения по умолчанию; владелец перекрывает их
в bot_settings (через /design, позже — через веб-панель).

Соглашения по ключам:
- <экран>.title / <экран>.text — заголовок и текст панели (core.panel_embed);
- <экран>.thumbnail — картинка панели; пусто = thumbnail.default,
  "none" = без картинки, "{bot_avatar}" = аватар бота;
- <префикс View>.<имя метода> — подпись кнопки (core.apply_texts);
- <префикс Modal>.title / .<поле> / .<поле>.placeholder — модалки;
- ключи на "color" — HEX-цвета вида 0x5865F2.
Подстановки в фразах — {name}; набор доступных подстановок у каждой фразы
свой и виден по дефолту.

Тип значения для веб-панели определяется по ключу: kind(key).
"""

CATALOG = {
    # ================= ОФОРМЛЕНИЕ =================
    "embed_color": "0x5865F2",
    "danger_color": "0xED4245",
    "thumbnail.default": "",
    "text_access_denied": "РЕПЛИКА ОС — ДОСТУП ЗАПРЕЩЁН",
    "nav_back": "◀️ Назад",
    "nav_next": "▶️ Далее",
    "nav_cancel": "❌ Отмена",

    # ================= ОБЩЕЕ =================
    "common.only_in_guild": "Эта функция работает только на сервере.",
    "common.pick_user": "Выберите пользователя",
    "common.pick_role": "Выберите роль",
    "common.not_enough_rights": "Недостаточно прав.",
    "common.need_admin": "Нужны права администратора.",
    "common.owner_only": "Настройки доступны только владельцу.",
    "common.cancelled": "Отменено.",
    "common.empty_list": "Пусто",
    "ping.reply": "🏓 Pong!",

    # ================= УРОВНИ ДОСТУПА =================
    "level.limited": "◽ Ограниченный пользователь",
    "level.member": "👤 Пользователь",
    "level.staff": "🔧 Staff",
    "level.admin": "🛡️ Администратор бота",
    "level.owner": "👑 Владелец",

    # ================= /access =================
    "access.home.title": "ACCESS MANAGER",
    "access.home.text": "Ваш уровень: {level}\n\nУправление пользователями, уровнями и доступом к командам.",
    "access.home.thumbnail": "{bot_avatar}",
    "access.home.users_button": "Пользователи",
    "access.home.commands_button": "Команды",
    "access.home.role_access_button": "Доступ по ролям",
    "access.home.denials_button": "Запреты",
    "access.home.settings_button": "⚙️ Настройки",

    "access.expires_never": "Постоянный",
    "access.users.title": "ПОЛЬЗОВАТЕЛИ",
    "access.users.text": "Выберите пользователя для просмотра и изменения уровня доступа.",
    "access.user.title": "ПОЛЬЗОВАТЕЛЬ",
    "access.user.text": "**Пользователь:** {user}\n\n**Уровень:** {level}\n**Действует до:** {expires}",
    "access.user.limited_button": "Ограниченный",
    "access.user.member_button": "Обычный участник",
    "access.user.staff_button": "Staff",
    "access.user.admin_button": "Администратор",
    "access.user.cannot_assign": "У вас недостаточно прав для назначения этого уровня.",

    "access.duration.title": "СРОК ДЕЙСТВИЯ",
    "access.duration.text": "{user} → {level}\n\nНа какой срок?",
    "access.duration.forever": "Навсегда",
    "access.duration.one_day": "1 день",
    "access.duration.one_week": "7 дней",
    "access.duration.custom": "Свой срок",
    "access.duration.done": "{user} → {level} ({until})",
    "access.duration.done_hours": "{user} → {level} на {hours} ч.",
    "access.duration.forever_word": "навсегда",
    "access.duration_modal.title": "СВОЙ СРОК",
    "access.duration_modal.hours": "На сколько часов",
    "access.duration_modal.hours.placeholder": "Например: 12",
    "access.duration_modal.bad_hours": "Введи целое число часов больше нуля.",

    "access.commands.title": "КОМАНДЫ",
    "access.commands.text": "Выберите команду для просмотра и настройки доступа.",
    "access.command.title": "COMMAND ACCESS",
    "access.command.text": (
        "**Команда:** `/{command}`\n**Описание:** {description}\n\n"
        "**Минимальный уровень:** {level}\n\n**Индивидуальный доступ:**\n{users}"
    ),
    "access.command.no_users": "Индивидуального доступа нет.",
    "access.command.level_unset": "Не задан",
    "access.command.no_description": "Без описания",
    "access.command.add_user": "Добавить",
    "access.command.remove_user": "Убрать",
    "access.command_add.title": "ДОБАВИТЬ ДОСТУП",
    "access.command_add.text": "Выберите пользователя для `/{command}`.",
    "access.command_remove.title": "УБРАТЬ ДОСТУП",
    "access.command_remove.text": "Выберите пользователя, у которого нужно убрать доступ к `/{command}`.",
    "access.command_duration.title": "СРОК ДОСТУПА",
    "access.command_duration.text": "На какой срок выдать доступ к `/{command}` для {user}?",

    "access.roles.title": "ДОСТУП ПО РОЛЯМ",
    "access.roles.text": "Выберите Discord-роль и назначьте ей уровень доступа.",
    "access.role.title": "ДОСТУП РОЛИ",
    "access.role.text": "{role}\n\nВыберите уровень доступа для обладателей этой роли.",
    "access.role.limited": "Ограниченный",
    "access.role.member": "Пользователь",
    "access.role.staff": "Staff",
    "access.role.admin": "Администратор",
    "access.role.remove": "Убрать",

    "access.denials.title": "ЗАПРЕТ ДОСТУПА",
    "access.denials.text": "Запрет полностью блокирует использование бота пользователем.\n\n{users}",
    "access.denials.empty": "Никто не забанен.",
    "access.denials.no_reason": "без причины",
    "access.denials.default_reason": "Access Manager",
    "access.deny_confirm.title": "⚠️ ПОДТВЕРДИ ЗАПРЕТ",
    "access.deny_confirm.text": "{user} будет полностью заблокирован в боте. Продолжить?",
    "access.deny_confirm.confirm": "Подтвердить запрет",

    "access.settings.title": "⚙️ БУНКЕР",
    "access.settings.text": "Owner-only инструменты бота.",
    "access.settings.backup": "Бэкап bot.db",
    "access.settings.denials": "Денаи",
    "access.settings.registry": "Action Registry",
    "access.settings.restart": "Перезапуск",
    "access.settings.no_db": "bot.db не найден.",
    "access.settings.restarting": "Останавливаю бота. Процесс-менеджер должен поднять его заново.",

    "access.registry.title": "ACTION REGISTRY",
    "access.registry.text": "Кто может создавать кнопки с каким действием.\n\n{actions}",
    "access.registry.empty": "Реестр пуст.",
    "access.action.text": "Изменить минимальный уровень или включить/выключить действие.",
    "access.action.member": "Member",
    "access.action.staff": "Staff",
    "access.action.admin": "Admin",
    "access.action.enable": "Включить",
    "access.action.disable": "Выключить",

    # ================= ОБЩИЕ ДЕЙСТВИЯ КНОПОК =================
    "common.default_button_label": "Кнопка",
    "common.yes": "да",
    "common.no": "нет",
    "actions.default.message": "РЕПЛИКА ОС — действие выполнено.",
    "actions.default.confirm": "РЕПЛИКА ОС — подтверждение получено.",
    "actions.default.ephemeral": "РЕПЛИКА ОС — это приватное сообщение.",

    # ================= ДЕЙСТВИЯ КНОПОК (action registry) =================
    "actions.not_configured": "Действие не настроено.",
    "actions.no_access": "У тебя нет доступа к этому действию.",
    "actions.wip": "РЕПЛИКА ОС — действие `{action}` пока в разработке.",
    "actions.cancelled": "Действие отменено.",
    "actions.dangerous.text": "⚠️ Действие `{action}` может изменить данные или отправить сообщение. Продолжить?",
    "actions.dangerous.confirm": "Подтвердить",
    "actions.edit_denied": "Редактировать сообщения могут только администратор и владелец.",
    "actions.edit_no_message": "Исходное сообщение недоступно для редактирования.",
    "actions.edit_modal.title": "РЕДАКТИРОВАТЬ СООБЩЕНИЕ",
    "actions.edit_modal.content_input": "Новый текст сообщения",
    "actions.edit_modal.empty": "Нельзя сохранить пустое сообщение: добавь текст.",
    "actions.edit_modal.gone": "Сообщение уже удалено и недоступно для редактирования.",
    "actions.edit_modal.forbidden": "У бота нет права редактировать это сообщение.",
    "actions.edit_modal.done": "Сообщение обновлено.",
    "actions.webhook_modal.title": "ОТПРАВИТЬ ЧЕРЕЗ WEBHOOK",
    "actions.webhook_modal.url_input": "Webhook URL",
    "actions.webhook_modal.content_input": "Текст сообщения",
    "actions.webhook_modal.no_url": "Укажи URL webhook.",
    "actions.webhook_modal.failed": "Не удалось отправить сообщение через webhook.",
    "actions.webhook_modal.sent": "Сообщение через webhook отправлено.",
    "actions.form_trigger.bad_value": "Для form.trigger укажи ID формы.",
    "actions.select_trigger.bad_value": "Для select.trigger укажи: role, user, channel или mentionable.",
    "actions.select_trigger.prompt": "Выбери значение:",
    "actions.role.bad_value": "Для действия с ролью укажи ID роли.",
    "actions.role.no_manage_roles": "У бота нет права Manage Roles.",
    "actions.role.unreachable": "Роль не найдена или находится выше роли бота.",
    "actions.role.forbidden": "Discord запретил изменение роли.",
    "actions.role.assigned": "Роль выдана.",
    "actions.role.removed": "Роль снята.",
    "actions.build_trigger.bad_value": "Для build.trigger укажи ID Message Build.",

    # ================= /embed (Message Build) =================
    "embed.home.title": "MESSAGE BUILD",
    "embed.home.text": (
        "Собери сообщение из embed'ов, добавь кнопки/форму/список и отправь пакетом в нужные каналы.\n\n"
        "С чего начнём?"
    ),
    "embed.home.create": "Создать новый",
    "embed.home.saved": "Мои сохранённые",
    "embed.home.use_template": "Использовать шаблон",
    "embed.default_name": "Новый Message Build",
    "embed.build_not_found": "Message Build не найден.",
    "embed.build_empty": "Этот Message Build пустой.",
    "embed.delete_denied": "Удалить может только создатель.",
    "embed.preview_footer": "Embed {n}/{total} · видимость: {visibility}",

    "embed.saved.title": "СОХРАНЁННЫЕ MESSAGE BUILD",
    "embed.saved.text": "Выбери, чтобы открыть предпросмотр и действия.",
    "embed.saved.empty": "Сохранённых Message Build нет",
    "embed.build_card.title": "MESSAGE BUILD",
    "embed.build_card.text": "Видимость: `{visibility}`",
    "embed.templates.title": "ШАБЛОНЫ",
    "embed.templates.text": "Выбери message-шаблон.",
    "embed.templates.empty": "Шаблонов ещё нет",

    "embed.visibility.title": "ВИДИМОСТЬ",
    "embed.visibility.text": "Кто сможет видеть и использовать это сообщение?",
    "embed.visibility.public": "Публичный",
    "embed.visibility.private": "Приватный",
    "embed.visibility.restricted": "Ограниченный",
    "embed.restriction.title": "ОГРАНИЧЕННЫЙ ДОСТУП",
    "embed.restriction.text": "По уровню доступа или по конкретной роли?",
    "embed.restriction.by_level": "По уровню доступа",
    "embed.restriction.by_role": "По роли(ям)",
    "embed.restriction_level.title": "УРОВЕНЬ",
    "embed.restriction_level.text": "Кто минимум сможет видеть это сообщение?",
    "embed.restriction_level.staff": "Staff",
    "embed.restriction_level.admin": "Admin",
    "embed.restriction_roles.title": "РОЛИ",
    "embed.restriction_roles.text": "Выбери до 5 ролей.",
    "embed.restriction_roles.placeholder": "Выбери роль(и)",

    "embed.switch.placeholder": "Переключить embed",
    "embed.switch.option": "Embed {n}",
    "embed.switch.add": "➕ Добавить embed",
    "embed.editor.basic": "Основное",
    "embed.editor.media": "Изображения",
    "embed.editor.author_footer": "Author/Footer",
    "embed.editor.add_field": "Добавить поле",
    "embed.editor.image_library": "Библиотека изображений",
    "embed.editor.confirm": "Подтвердить дизайн",
    "embed.editor.too_many_fields": "В одном embed максимум 25 полей.",
    "embed.editor.library_wip": "Библиотека изображений в разработке.",
    "embed.basic_modal.title": "ОСНОВНОЕ",
    "embed.basic_modal.title_input": "Title",
    "embed.basic_modal.description_input": "Description",
    "embed.basic_modal.color_input": "Цвет HEX",
    "embed.basic_modal.bad_color": "Некорректный HEX-цвет.",
    "embed.media_modal.title": "ИЗОБРАЖЕНИЯ",
    "embed.media_modal.thumbnail_input": "Thumbnail URL",
    "embed.media_modal.image_input": "Image URL",
    "embed.author_modal.title": "AUTHOR / FOOTER",
    "embed.author_modal.author_input": "Author name",
    "embed.author_modal.footer_input": "Footer",
    "embed.field_modal.title": "ПОЛЕ",
    "embed.field_modal.name_input": "Название",
    "embed.field_modal.value_input": "Значение",
    "embed.field_modal.inline_input": "Inline? yes/no",

    "embed.interactive.title": "ИНТЕРАКТИВ",
    "embed.interactive.text": "Нужны кнопки, форма или выбор? Выбери из списка или сразу жми «Далее», если не нужно ничего.",
    "embed.interactive.placeholder": "Не выбрано — можно пропустить",
    "embed.interactive.option_form": "Форма",
    "embed.interactive.option_list": "Открывающийся список",
    "embed.interactive.option_select": "Выбор (роль/участник/канал)",
    "embed.interactive.option_buttons": "Кнопки",
    "embed.interactive.next_step": "Далее",
    "embed.form_step.title": "FORM BUILDER",
    "embed.form_step.text": "Настрой форму. По завершении сохрани её отдельно — Message Build сохранится следующим шагом.",

    "embed.list.title": "ОТКРЫВАЮЩИЙСЯ СПИСОК",
    "embed.list.text": "Добавь опции списка.",
    "embed.list.add_option": "Добавить опцию",
    "embed.list.done": "Готово",
    "embed.list.too_many": "Максимум 25 опций в select.",
    "embed.list.pick_action": "Какое действие у этой опции?",
    "embed.list.option_added": "Опция «{label}» добавлена. Всего: {total}.",
    "embed.list.placeholder": "Выбери опцию",
    "embed.list.default_option": "Опция",
    "embed.list.option_missing": "Опция не найдена.",
    "embed.list_option_modal.title": "ОПЦИЯ СПИСКА",
    "embed.list_option_modal.label_input": "Текст опции",
    "embed.list_option_modal.description_input": "Описание",
    "embed.list_option_modal.emoji_input": "Emoji",
    "embed.list_value_modal.title": "ЗНАЧЕНИЕ ОПЦИИ",
    "embed.list_value_modal.value_input": "Текст ответа при выборе",
    "embed.pick_action": "Выбери действие",
    "embed.no_actions": "Нет доступных действий",
    "embed.no_actions_allowed": "Тебе не разрешено ни одно действие из реестра.",

    "embed.native_select.title": "ВЫБОР",
    "embed.native_select.text": "Какой тип выбора нужен?",
    "embed.native_select.role": "Роль",
    "embed.native_select.user": "Участник",
    "embed.native_select.channel": "Канал",
    "embed.native_select.mentionable": "Mentionable",
    "embed.native_select.placeholder": "Выбери...",

    "embed.buttons.title": "КНОПКИ",
    "embed.buttons.text": "До {max} кнопок.",
    "embed.buttons.added": "Добавлено: {count}/{max}.",
    "embed.buttons.add": "Добавить кнопку",
    "embed.buttons.done": "Готово",
    "embed.buttons.too_many": "Максимум 5 кнопок.",
    "embed.button_label_modal.title": "ТЕКСТ КНОПКИ",
    "embed.button_label_modal.label_input": "Текст кнопки",
    "embed.button_color.title": "ЦВЕТ КНОПКИ",
    "embed.button_color.text": "Выбери стиль (Discord поддерживает только эти 5, кастомный HEX недоступен).",
    "embed.button_color.blue": "🔵 Синяя",
    "embed.button_color.grey": "⚪ Серая",
    "embed.button_color.green": "🟢 Зелёная",
    "embed.button_color.red": "🔴 Красная",
    "embed.button_color.link": "🔗 Ссылка",
    "embed.button_action.title": "ДЕЙСТВИЕ",
    "embed.button_action.text": "Что должна делать кнопка? Список зависит от твоего уровня доступа.",
    "embed.button_value_modal.title": "ЗНАЧЕНИЕ",
    "embed.button_value_modal.value_input": "URL или текст действия",

    "embed.saved_build.title": "MESSAGE BUILD СОХРАНЁН",
    "embed.saved_build.text": "ID: `{id}` · embed'ов: {embeds} · кнопок: {buttons}",
    "embed.final.preview": "Предпросмотр",
    "embed.final.send": "Отправить",
    "embed.final.save_template_button": "Сохранить как шаблон",
    "embed.final.delete": "Удалить",
    "embed.deleted.title": "MESSAGE BUILD УДАЛЁН",
    "embed.send.placeholder": "Куда отправить",
    "embed.send.prompt": "Выбери канал(ы):",
    "embed.send.sent": "Отправлено: {channels}",
    "embed.send.failed": "Не удалось:\n{errors}",
    "embed.send.channel_missing": "{channel} — канал не найден",
    "embed.send.forbidden": "{channel} — нет прав на отправку",
    "embed.send.http_error": "{channel} — ошибка Discord: `{error}`",
    "embed.save_template_modal.title": "СОХРАНИТЬ КАК ШАБЛОН",
    "embed.save_template_modal.name_input": "Название шаблона",
    "embed.save_template_modal.category_input": "Категория",
    "embed.save_template_modal.done": "Сохранено как шаблон `{id}`.",

    # ================= /buttons =================
    "buttons.home.title": "BUTTON BUILDER",
    "buttons.home.text": (
        "Отдельный конструктор кнопок.\n\n"
        "Максимум **{max} кнопок** в одном наборе.\n"
        "Набор можно будет подключать к Message Build."
    ),
    "buttons.home.create": "Создать набор",
    "buttons.home.saved": "Сохранённые наборы",
    "buttons.default_name": "Новый набор кнопок",
    "buttons.builder.title": "BUTTON BUILDER",
    "buttons.builder.text": "Можно добавить до {max} кнопок.\n\n{buttons}",
    "buttons.builder.line": "{n}. {emoji} {label} · {action}",
    "buttons.builder.empty": "Кнопок пока нет.",
    "buttons.builder.need_button": "Добавь хотя бы одну кнопку.",
    "buttons.builder.add": "Добавить кнопку",
    "buttons.builder.done": "Готово",
    "buttons.builder.clear": "Очистить",
    "buttons.limit": "Лимит достигнут: максимум {max} кнопок.",
    "buttons.modal.title": "НОВАЯ КНОПКА",
    "buttons.modal.label_input": "Текст кнопки",
    "buttons.modal.emoji_input": "Emoji",
    "buttons.modal.emoji_input.placeholder": "Например: ✨ или :my_emoji:",
    "buttons.modal.style_input": "Стиль: primary / secondary / success / danger",
    "buttons.modal.action_input": "Действие: link / message / confirm",
    "buttons.modal.value_input": "URL или текст действия",
    "buttons.modal.bad_style": "Стиль должен быть: primary, secondary, success или danger.",
    "buttons.modal.bad_action": "Действие должно быть: link, message или confirm.",
    "buttons.modal.need_url": "Для link нужен URL.",
    "buttons.saved_set.title": "BUTTON SET СОХРАНЁН",
    "buttons.saved_set.text": "ID: `{id}`\nКнопок: **{count}**",
    "buttons.list.title": "BUTTON SETS",
    "buttons.list.text": "Выберите сохранённый набор.",
    "buttons.list.empty": "Сохранённых наборов нет",
    "buttons.not_found": "Набор не найден.",
    "buttons.card.title": "НАБОР КНОПОК",
    "buttons.card.text": "Категория: `{category}`\nВидимость: `{visibility}`\nКнопок: `{count}`",

    # ================= /forms =================
    "forms.home.title": "FORM BUILDER",
    "forms.home.text": "Создание форм, приватных заявок, reviewers и действий после решения.",
    "forms.start.create": "Создать",
    "forms.start.saved": "Сохранённые",
    "forms.default_name": "Новая форма",
    "forms.builder.title": "FORM BUILDER",
    "forms.builder.text": (
        "**Название:** {name}\n**Категория:** {category}\n**Видимость:** {visibility}\n"
        "**Канал заявок:** {destination}\n"
        "**Reviewers:** {reviewer_roles} ролей / {reviewer_users} пользователей\n"
        "**После решения:** {post_action}\n**Роль после одобрения:** {post_role}\n\n**Вопросы:**\n{questions}"
    ),
    "forms.builder.question_line": "{n}. {label} · {type} · {required}",
    "forms.builder.no_questions": "нет",
    "forms.builder.channel_unset": "не задан",
    "forms.builder.role_unset": "не задана",
    "forms.builder.need_question": "Нужны хотя бы один вопрос и канал заявок.",
    "forms.builder.basic": "Основные",
    "forms.builder.question": "Вопрос",
    "forms.builder.routing": "Маршрутизация",
    "forms.builder.target": "Роль для заявки",
    "forms.builder.save": "Сохранить",
    "forms.question.required": "required",
    "forms.question.optional": "optional",
    "forms.basic_modal.title": "ОСНОВНЫЕ ДАННЫЕ ФОРМЫ",
    "forms.basic_modal.name": "Название",
    "forms.basic_modal.description": "Описание",
    "forms.basic_modal.category": "Категория",
    "forms.basic_modal.visibility": "private/public",
    "forms.basic_modal.roles": "Разрешённые role ID через запятую",
    "forms.basic_modal.bad_visibility": "Видимость: private или public.",
    "forms.question_modal.title": "ВОПРОС ФОРМЫ",
    "forms.question_modal.label": "Вопрос",
    "forms.question_modal.qtype": "short / long / yesno",
    "forms.question_modal.required": "required? yes/no",
    "forms.question_modal.bad_type": "Тип: short, long или yesno.",
    "forms.question_modal.too_many": "Максимум {max} вопросов для одного Discord Modal.",
    "forms.routing_modal.title": "МАРШРУТИЗАЦИЯ ФОРМЫ",
    "forms.routing_modal.destination": "ID канала заявок",
    "forms.routing_modal.reviewer_roles": "Reviewer role IDs через запятую",
    "forms.routing_modal.reviewer_users": "Reviewer user IDs через запятую",
    "forms.routing_modal.action": "review / role / none",
    "forms.routing_modal.role": "Role ID после одобрения",
    "forms.routing_modal.invalid": "Проверь ID канала и действие.",
    "forms.target_role.title": "TARGET ROLE",
    "forms.target_role.text": "Выберите роль, на которую человек подаёт заявку.",
    "forms.target_role.placeholder": "Роль, на которую подаётся заявка",
    "forms.saved.title": "ФОРМА СОХРАНЕНА",
    "forms.saved.text": "ID: `{id}`\nКанал заявок: {channel}\nРоль: {role}",
    "forms.use.apply": "Подать заявку",
    "forms.not_found": "Форма не найдена.",
    "forms.unavailable": "Форма недоступна.",
    "forms.no_description": "Без описания",
    "forms.card.title": "ФОРМА",
    "forms.list.title": "FORMS",
    "forms.list.text": "Выберите форму.",
    "forms.list.empty": "Форм пока нет",
    "forms.submitted": "РЕПЛИКА ОС — заявка отправлена приватно. Reviewers получат её в настроенном канале.",
    "forms.submission.title": "НОВАЯ ЗАЯВКА",
    "forms.submission.text": "Форма: **{form}**\nЗаявитель: {user}\nID: `{id}`",
    "forms.review.approve": "Одобрить",
    "forms.review.reject": "Отклонить",
    "forms.review.not_found": "Заявка не найдена.",
    "forms.review.no_rights": "У вас нет права рассматривать эту заявку.",
    "forms.review.already": "Уже обработано: {status}.",
    "forms.review.role_forbidden": "Discord не разрешил выдать роль. Проверь права бота и иерархию ролей.",
    "forms.review.role_missing": "Не удалось найти участника или роль для назначения.",
    "forms.reviewed.title": "ЗАЯВКА ОБРАБОТАНА",
    "forms.reviewed.text": "Статус: **{status}**\nReviewer: {reviewer}",
    "forms.status.pending": "pending",
    "forms.status.approved": "approved",
    "forms.status.rejected": "rejected",

    # ================= /templates =================
    "templates.home.title": "TEMPLATE MANAGER",
    "templates.home.text": "Публичные / приватные шаблоны. Владелец видит все; доступ можно ограничить ролями.",
    "templates.home.list": "Список",
    "templates.home.save": "Сохранить JSON",
    "templates.list.title": "ШАБЛОНЫ",
    "templates.list.text": "Доступные вам шаблоны.",
    "templates.list.empty": "Шаблонов нет",
    "templates.card.title": "ШАБЛОН",
    "templates.card.text": "Type: `{type}`\nCategory: `{category}`\nVisibility: `{visibility}`\nИзбранное: **{favorite}**",
    "templates.card.use": "Использовать",
    "templates.card.favorite": "Избранное",
    "templates.card.delete": "Удалить",
    "templates.button_set.title": "НАБОР КНОПОК",
    "templates.button_set.text": "Набор кнопок.",
    "templates.deleted.title": "ШАБЛОН УДАЛЁН",
    "templates.not_found": "Шаблон не найден.",
    "templates.unavailable": "Шаблон недоступен.",
    "templates.empty": "Этот шаблон пустой и не может быть показан.",
    "templates.form_hint": "Для формы используй сохранённый Form ID в payload.",
    "templates.delete_denied": "Удалять может создатель или владелец.",
    "templates.modal.title": "СОХРАНИТЬ ШАБЛОН",
    "templates.modal.name": "Название",
    "templates.modal.typ": "message / buttons / form",
    "templates.modal.category_visibility": "Категория/видимость (general/public)",
    "templates.modal.roles": "Role IDs через запятую",
    "templates.modal.payload": "JSON payload",
    "templates.modal.bad_type": "Проверь тип и поле `категория/private` или `категория/public`.",
    "templates.modal.bad_json": "JSON некорректен.",
    "templates.modal.saved": "Шаблон сохранён: `{id}`",

    # ================= /webhooks =================
    "webhooks.home.title": "WEBHOOK MANAGER",
    "webhooks.home.text": "Создать · удалить · переименовать · аватар · отправка · тест · история · безопасный URL.",
    "webhooks.home.create": "Создать",
    "webhooks.home.list": "Список",
    "webhooks.home.history": "История",
    "webhooks.create_modal.title": "СОЗДАТЬ WEBHOOK",
    "webhooks.create_modal.name": "Название",
    "webhooks.create_modal.avatar": "Avatar URL",
    "webhooks.pick_channel": "Выберите канал.",
    "webhooks.channel_placeholder": "Канал",
    "webhooks.need_manage": "Нужны права Manage Webhooks.",
    "webhooks.discord_error": "Ошибка Discord: `{error}`",
    "webhooks.error": "Ошибка: `{error}`",
    "webhooks.created.title": "WEBHOOK СОЗДАН",
    "webhooks.created.text": "Канал: {channel}\nИмя: **{name}**\nID: `{id}`\n\n🔒 URL скрыт.",
    "webhooks.list.title": "WEBHOOKS",
    "webhooks.list.text": "Сохранённые webhook. URL скрыты.",
    "webhooks.list.empty": "Webhook нет",
    "webhooks.not_found": "Webhook не найден.",
    "webhooks.card.title": "WEBHOOK",
    "webhooks.card.text": "Имя: **{name}**\nКанал: {channel}\nID: `{id}`\n\n🔒 URL скрыт.",
    "webhooks.card.show": "Показать URL",
    "webhooks.card.send": "Отправить",
    "webhooks.card.rename": "Переименовать",
    "webhooks.card.avatar": "Аватар",
    "webhooks.card.test": "Тест",
    "webhooks.card.history": "История",
    "webhooks.card.delete": "Удалить",
    "webhooks.card.regenerate": "Пересоздать URL",
    "webhooks.access_denied": "Доступ запрещён.",
    "webhooks.url": "🔑 `{url}`\n\nНе публикуй этот URL.",
    "webhooks.test_message": "Webhook Manager · тестовое сообщение.",
    "webhooks.test_sent": "Тест отправлен.",
    "webhooks.history.title": "WEBHOOK HISTORY",
    "webhooks.history.empty": "История пуста.",
    "webhooks.delete.confirm": "⚠️ Webhook будет удалён. Подтвердить?",
    "webhooks.delete.yes": "Удалить",
    "webhooks.delete.done": "Webhook удалён. Старый URL больше не работает.",
    "webhooks.regenerate.owner_only": "Пересоздавать URL может только владелец.",
    "webhooks.regenerate.confirm": "⚠️ Старый URL перестанет работать. Подтвердить?",
    "webhooks.regenerate.yes": "Да, пересоздать",
    "webhooks.regenerate.done": "♻️ URL пересоздан. Старый URL больше не работает.",
    "webhooks.message_modal.title": "WEBHOOK MESSAGE",
    "webhooks.message_modal.text": "Текст",
    "webhooks.message_modal.embed_title": "Embed title",
    "webhooks.message_modal.description": "Embed description",
    "webhooks.message_modal.image": "Image URL",
    "webhooks.message_modal.thumbnail": "Thumbnail URL",
    "webhooks.message_modal.empty": "Добавь текст или данные для embed.",
    "webhooks.message_modal.sent": "Отправлено через webhook.",
    "webhooks.rename_modal.title": "ПЕРЕИМЕНОВАТЬ WEBHOOK",
    "webhooks.rename_modal.name": "Новое имя",
    "webhooks.rename_modal.done": "Имя изменено.",
    "webhooks.avatar_modal.title": "ИЗМЕНИТЬ АВАТАР",
    "webhooks.avatar_modal.avatar": "Прямая URL-ссылка",
    "webhooks.avatar_modal.fetch_failed": "Не удалось получить изображение.",
    "webhooks.avatar_modal.done": "Аватар изменён.",

    # ================= /select =================
    "select.home.title": "SELECT MENU",
    "select.home.text": "Роли, каналы и пользователи. Выбор роли можно связать с Forms.",
    "select.home.role": "Выбор роли",
    "select.home.channel": "Выбор канала",
    "select.home.user": "Выбор пользователя",
    "select.role.title": "ROLE SELECT",
    "select.role.text": "Выберите роль в списке.",
    "select.picked": "Выбрано: {value}",
    "select.channel_hint": "Выбор каналов используется в Message/Webhook/Forms панелях.",
    "select.user_hint": "Выбор пользователей используется в Access Manager и Forms.",

    # ================= /messages =================
    "messages.home.title": "MESSAGE MANAGER",
    "messages.home.text": "Предпросмотр, отправка и удаление сохранённых Message Build.",
    "messages.list.empty": "Build пока нет",
    "messages.not_found": "Build не найден.",
    "messages.empty": "Этот Message Build пустой и не может быть показан.",

    # ================= /panel (веб-панель) =================
    "panel.link": "Ссылка на веб-панель. Одноразовая, действует 10 минут — никому не пересылай.",
    "panel.open": "Открыть панель",
    "panel.disabled": (
        "Веб-панель не настроена: добавь в .env `WEB_PANEL_PORT` (порт из вкладки Network) "
        "и `WEB_PANEL_URL` (например `http://1.2.3.4:25565`), затем перезапусти бота."
    ),

    # ================= /design =================
    "design.title": "DESIGN",
    "design.text": (
        "Настройки оформления бота.\n\n"
        "Основной цвет: `{embed_color}`\nОпасный цвет: `{danger_color}`\n"
        "Отказ в доступе: {text_access_denied}\nНазад: {nav_back}\nОтмена: {nav_cancel}"
    ),
    "design.edit": "Изменить",
    "design.preview": "Предпросмотр",
    "design.reset": "Сбросить",
    "design.bad_color": "Цвета должны быть в формате `#RRGGBB`.",
    "design.modal.title": "DESIGN SETTINGS",
    "design.modal.embed_color_input": "Основной HEX цвет",
    "design.modal.danger_color_input": "Опасный HEX цвет",
    "design.modal.denied_input": "Текст отказа",
    "design.modal.back_input": "Текст кнопки Назад",
    "design.modal.cancel_input": "Текст кнопки Отмена",
}


def kind(key):
    """Тип значения для редактора: color / image / text."""
    if key.endswith("color"):
        return "color"
    if key.endswith("thumbnail"):
        return "image"
    return "text"
