"""
texts.py
========
Каталог всего, что видит пользователь бота: фразы, подписи кнопок и полей,
цвета, thumbnails. Здесь — значения по умолчанию; владелец перекрывает их
в bot_settings (через /design, позже — через веб-панель).

Соглашения по ключам:
- <экран>.title / <экран>.text — заголовок и текст панели (core.panel_embed);
- <экран>.thumbnail — картинка панели; пусто = thumbnail.default,
  "none" = без картинки, "{bot_avatar}" = аватар бота;
- <префикс View>.<имя метода> — подпись кнопки (core.apply_texts);
- <префикс Modal>.title / .<поле> / .<поле>.placeholder — модалки;
- ключи на "color" — HEX-цвета вида 0x5865F2.
Подстановки в фразах — {name}; набор доступных подстановок у каждой фразы
свой и виден по дефолту.

Тип значения для веб-панели определяется по ключу: kind(key).
"""

CATALOG = {
    # ================= ОФОРМЛЕНИЕ =================
    "embed_color": "0x5865F2",
    "danger_color": "0xED4245",
    "thumbnail.default": "",
    # Картинки команд: экран без своей картинки берёт картинку своей команды,
    # а та — общую (*.default). "none" — без картинки. Размеры — docs/DESIGN_ASSETS.md.
    "thumbnail.embed": "",
    "thumbnail.forms": "",
    "thumbnail.access": "",
    "thumbnail.buttons": "",
    "thumbnail.templates": "",
    "thumbnail.webhooks": "",
    "thumbnail.select": "",
    "thumbnail.logo": "",
    "banner.default": "",
    "banner.embed": "",
    "banner.forms": "",
    "banner.access": "",
    "banner.buttons": "",
    "banner.templates": "",
    "banner.webhooks": "",
    "banner.select": "",
    "banner.logo": "",
    "text_access_denied": "РЕПЛИКА ОС — ДОСТУП ЗАПРЕЩЁН",
    "nav_back": "◀️ Назад",
    "nav_next": "▶️ Далее",
    "nav_cancel": "❌ Отмена",

    # ================= ОБЩЕЕ =================
    "common.only_in_guild": "Эта функция работает только на сервере.",
    "common.pick_user": "Выберите пользователя",
    "common.pick_role": "Выберите роль",
    "common.not_enough_rights": "Недостаточно прав.",
    "common.need_admin": "Нужны права администратора.",
    "common.owner_only": "Настройки доступны только владельцу.",
    "common.cancelled": "Отменено.",
    "common.empty_list": "Пусто",

    # ================= УРОВНИ ДОСТУПА =================
    "level.limited": "◽ Ограниченный пользователь",
    "level.member": "👤 Пользователь",
    "level.staff": "🔧 Staff",
    "level.admin": "🛡️ Администратор бота",
    "level.owner": "👑 Владелец",

    # ================= /access =================
    "access.home.title": "ACCESS MANAGER",
    "access.home.text": 'Кто что может делать с ботом: уровни людей и ролей, доступ к командам, запреты и журнал действий.\n\nТвой уровень: {level}',
    "access.home.thumbnail": "{bot_avatar}",
    "access.home.users_button": "Пользователи",
    "access.home.commands_button": "Команды",
    "access.home.role_access_button": "Доступ по ролям",
    "access.home.denials_button": "Запреты",
    "access.home.settings_button": "⚙️ Настройки",

    "access.expires_never": "Постоянный",
    "access.users.title": "ПОЛЬЗОВАТЕЛИ",
    "access.users.text": "Выберите пользователя для просмотра и изменения уровня доступа.",
    "access.user.title": "ПОЛЬЗОВАТЕЛЬ",
    "access.user.text": "**Пользователь:** {user}\n\n**Уровень:** {level}\n**Действует до:** {expires}",
    "access.user.limited_button": "Ограниченный",
    "access.user.member_button": "Обычный участник",
    "access.user.staff_button": "Staff",
    "access.user.admin_button": "Администратор",
    "access.user.cannot_assign": "У вас недостаточно прав для назначения этого уровня.",

    "access.duration.title": "СРОК ДЕЙСТВИЯ",
    "access.duration.text": "{user} → {level}\n\nНа какой срок?",
    "access.duration.forever": "Навсегда",
    "access.duration.one_day": "1 день",
    "access.duration.one_week": "7 дней",
    "access.duration.custom": "Свой срок",
    "access.duration.done": "{user} → {level} ({until})",
    "access.duration.done_hours": "{user} → {level} на {hours} ч.",
    "access.duration.forever_word": "навсегда",
    "access.duration_modal.title": "СВОЙ СРОК",
    "access.duration_modal.hours": "На сколько часов",
    "access.duration_modal.hours.placeholder": "Например: 12",
    "access.duration_modal.bad_hours": "Введи целое число часов больше нуля.",

    "access.commands.title": "КОМАНДЫ",
    "access.commands.text": "Выберите команду для просмотра и настройки доступа.",
    "access.command.title": "COMMAND ACCESS",
    "access.command.text": (
        "**Команда:** `/{command}`\n**Описание:** {description}\n\n"
        "**Минимальный уровень:** {level}\n\n**Индивидуальный доступ:**\n{users}"
    ),
    "access.command.no_users": "Индивидуального доступа нет.",
    "access.command.level_unset": "Не задан",
    "access.command.no_description": "Без описания",
    "access.command.add_user": "Добавить",
    "access.command.remove_user": "Убрать",
    "access.command_add.title": "ДОБАВИТЬ ДОСТУП",
    "access.command_add.text": "Выберите пользователя для `/{command}`.",
    "access.command_remove.title": "УБРАТЬ ДОСТУП",
    "access.command_remove.text": "Выберите пользователя, у которого нужно убрать доступ к `/{command}`.",
    "access.command_duration.title": "СРОК ДОСТУПА",
    "access.command_duration.text": "На какой срок выдать доступ к `/{command}` для {user}?",

    "access.roles.title": "ДОСТУП ПО РОЛЯМ",
    "access.roles.text": "Выберите Discord-роль и назначьте ей уровень доступа.",
    "access.role.title": "ДОСТУП РОЛИ",
    "access.role.text": "{role}\n\nВыберите уровень доступа для обладателей этой роли.",
    "access.role.limited": "Ограниченный",
    "access.role.member": "Пользователь",
    "access.role.staff": "Staff",
    "access.role.admin": "Администратор",
    "access.role.remove": "Убрать",

    "access.denials.title": "ЗАПРЕТ ДОСТУПА",
    "access.denials.text": "Запрет полностью блокирует использование бота пользователем.\n\n{users}",
    "access.denials.empty": "Никто не забанен.",
    "access.denials.no_reason": "без причины",
    "access.denials.default_reason": "Access Manager",
    "access.deny_confirm.title": "⚠️ ПОДТВЕРДИ ЗАПРЕТ",
    "access.deny_confirm.text": "{user} будет полностью заблокирован в боте. Продолжить?",
    "access.deny_confirm.confirm": "Подтвердить запрет",

    "access.settings.title": "⚙️ БУНКЕР",
    "access.settings.text": "Owner-only инструменты бота.",
    "access.settings.backup": "Бэкап bot.db",
    "access.settings.denials": "Денаи",
    "access.settings.registry": "Action Registry",
    "access.settings.restart": "Перезапуск",
    "access.settings.no_db": "bot.db не найден.",
    "access.settings.restarting": 'Останавливаю бота. На хостинге без авто-перезапуска запусти его снова в панели (Start).',

    "access.registry.title": "ACTION REGISTRY",
    "access.registry.text": "Кто может создавать кнопки с каким действием.\n\n{actions}",
    "access.registry.empty": "Реестр пуст.",
    "access.action.text": "Изменить минимальный уровень или включить/выключить действие.",
    "access.action.member": 'Создаёт: Member',
    "access.action.staff": 'Создаёт: Staff',
    "access.action.admin": 'Создаёт: Admin',
    "access.action.enable": "Включить",
    "access.action.disable": "Выключить",

    # ================= ОБЩИЕ ДЕЙСТВИЯ КНОПОК =================
    "common.default_button_label": "Кнопка",
    "common.yes": "да",
    "common.no": "нет",
    "actions.default.message": "РЕПЛИКА ОС — действие выполнено.",
    "actions.default.confirm": "РЕПЛИКА ОС — подтверждение получено.",
    "actions.default.ephemeral": "РЕПЛИКА ОС — это приватное сообщение.",

    # ================= ДЕЙСТВИЯ КНОПОК (action registry) =================
    "actions.not_configured": "Действие не настроено.",
    "actions.no_access": "У тебя нет доступа к этому действию.",
    "actions.wip": "РЕПЛИКА ОС — действие `{action}` пока в разработке.",
    "actions.cancelled": "Действие отменено.",
    "actions.dangerous.text": "⚠️ Действие `{action}` может изменить данные или отправить сообщение. Продолжить?",
    "actions.dangerous.confirm": "Подтвердить",
    "actions.edit_denied": "Редактировать сообщения могут только администратор и владелец.",
    "actions.edit_no_message": "Исходное сообщение недоступно для редактирования.",
    "actions.edit_modal.title": "РЕДАКТИРОВАТЬ СООБЩЕНИЕ",
    "actions.edit_modal.content_input": "Новый текст сообщения",
    "actions.edit_modal.empty": "Нельзя сохранить пустое сообщение: добавь текст.",
    "actions.edit_modal.gone": "Сообщение уже удалено и недоступно для редактирования.",
    "actions.edit_modal.forbidden": "У бота нет права редактировать это сообщение.",
    "actions.edit_modal.done": "Сообщение обновлено.",
    "actions.webhook_modal.title": "ОТПРАВИТЬ ЧЕРЕЗ WEBHOOK",
    "actions.webhook_modal.url_input": "Webhook URL",
    "actions.webhook_modal.content_input": "Текст сообщения",
    "actions.webhook_modal.no_url": "Укажи URL webhook.",
    "actions.webhook_modal.failed": "Не удалось отправить сообщение через webhook.",
    "actions.webhook_modal.sent": "Сообщение через webhook отправлено.",
    "actions.form_trigger.bad_value": "Для form.trigger укажи ID формы.",
    "actions.select_trigger.bad_value": "Для select.trigger укажи: role, user, channel или mentionable.",
    "actions.select_trigger.prompt": "Выбери значение:",
    "actions.role.bad_value": "Для действия с ролью укажи ID роли.",
    "actions.role.no_manage_roles": "У бота нет права Manage Roles.",
    "actions.role.unreachable": "Роль не найдена или находится выше роли бота.",
    "actions.role.forbidden": "Discord запретил изменение роли.",
    "actions.role.assigned": 'Роль {role} выдана.',
    "actions.role.removed": 'Роль {role} снята.',
    "actions.build_trigger.bad_value": "Для build.trigger укажи ID сохранённого Message Build этого сервера (ID видно в /messages).",

    # ================= /embed (Message Build) =================
    "embed.home.title": "MESSAGE BUILD",
    "embed.home.text": "Конструктор сообщений: собери пост из embed'ов, добавь кнопки, список или кнопку формы и отправь в каналы. Сохранённое сообщение можно потом править — отправленные копии обновятся.",
    "embed.home.create": "Создать новый",
    "embed.home.saved": "Мои сохранённые",
    "embed.home.use_template": "Использовать шаблон",
    "embed.home.from_message": "Из сообщения",
    "embed.final.export_json": "Экспорт JSON",
    "embed.final.history": "История",
    "build_tools.import_modal.title": "ИЗ СООБЩЕНИЯ",
    "live.error.author_gone": "автор этой отправки больше не на сервере",
    "live.error.thread_locked": "{channel} — ветка закрыта",
    "live.no_submissions": "заявок пока нет",
    "embed.final.schedule": "Расписание",
    "embed.final.triggers": "Триггеры",
    "embed.final.settings": "Настройки",
    "automation.denied": "Расписание, триггеры и настройки build'а — для staff и выше, и только у своих build'ов (админам — у всех).",
    "automation.too_many": "Достигнут лимит: {max}.",
    "automation.pick_channel": "Канал, ветка или форум",
    "automation.here": "📍 Сюда (где открыта панель)",
    "automation.anywhere": "везде",
    "automation.once": "один раз",
    "automation.every_minutes": "каждые {n} мин",
    "automation.every_hours": "каждые {n} ч",
    "automation.every_days": "каждые {n} д",
    "automation.every_weeks": "каждые {n} нед",
    "automation.status_on": "✅",
    "automation.status_off": "⏸ на паузе",
    "automation.status_error": "⚠️ {error}",
    "automation.error.author": "тот, кто это настроил, ушёл с сервера или потерял доступ к build'у",
    "automation.event.member_join": "новый участник",
    "automation.event.thread_create": "новая ветка/пост",
    "automation.event.keyword": "ключевое слово",
    "automation.schedules.title": "РАСПИСАНИЕ",
    "automation.schedules.text": (
        "Build сам уйдёт в канал, ветку или форум (в форуме — новым постом).\n"
        "Время — по часовому поясу `{tz}`; ниже оно показано в твоём.\n\n{list}"
    ),
    "automation.schedules.empty": "Расписаний нет.",
    "automation.schedules.add": "Добавить",
    "automation.schedules.manage": "Пауза или удаление…",
    "automation.schedule.line": "`#{id}` → {channel} · {when} · {repeat} · {status}",
    "automation.schedule.option": "#{id} · {repeat}",
    "automation.schedule_channel.title": "КУДА ОТПРАВЛЯТЬ",
    "automation.schedule_channel.text": "Выбери канал, ветку или форум. После выбора спрошу время.",
    "automation.schedule_modal.title": "РАСПИСАНИЕ",
    "automation.schedule_modal.when_input": "Когда",
    "automation.schedule_modal.when_input.placeholder": "18:30 · 25.12 18:30 · +2ч",
    "automation.schedule_modal.repeat_input": "Повтор (пусто — один раз)",
    "automation.schedule_modal.repeat_input.placeholder": "1д · 12ч · 1 неделя",
    "automation.schedule_item.toggle": "Пауза / включить",
    "automation.schedule_item.remove": "Удалить",
    "automation.schedule_item.back": "Назад",
    "automation.bad_when": "Не поняла время. Примеры: `18:30`, `25.12 18:30`, `25.12.2026 9:00`, `+30м`, `через 2ч`. Время должно быть в будущем.",
    "automation.bad_interval": "Повтор: пусто (один раз) или например `1д`, `12ч`, `1 неделя`. Не чаще раза в {min} минут.",
    "automation.triggers.title": "ТРИГГЕРЫ",
    "automation.triggers.text": (
        "Build сам отправится, когда что-то случится. В тексте можно использовать "
        "`{{user}}` — того, на ком сработал триггер.\n\n{list}"
    ),
    "automation.triggers.empty": "Триггеров нет.",
    "automation.triggers.member_join": "Новый участник",
    "automation.triggers.thread_create": "Новая ветка / пост",
    "automation.triggers.keyword": "Ключевое слово",
    "automation.triggers.manage": "Пауза или удаление…",
    "automation.trigger.line": "`#{id}` {what} · {status}",
    "automation.trigger.option": "#{id} · {event}",
    "automation.trigger.member_join": "👋 новый участник → {channel}",
    "automation.trigger.thread_create": "🧵 новая ветка/пост в {channel} → ответ в эту ветку",
    "automation.trigger.keyword": "💬 «{words}» в {channel} → ответ там же",
    "automation.trigger_target.title": "КУДА ПРИВЕТСТВОВАТЬ",
    "automation.trigger_target.text": "Куда отправлять build, когда на сервер заходит новый участник?",
    "automation.trigger_watch_threads.title": "ГДЕ СЛЕДИТЬ",
    "automation.trigger_watch_threads.text": "В каком форуме или канале следить за новыми ветками? Build уйдёт прямо в новую ветку/пост.",
    "automation.keyword_modal.title": "КЛЮЧЕВОЕ СЛОВО",
    "automation.keyword_modal.words_input": "Слова или фразы через запятую",
    "automation.keyword_modal.cooldown_input": "Пауза между ответами, сек (от 10)",
    "automation.keyword.empty": "Укажи хотя бы одно слово.",
    "automation.keyword.bad_cooldown": "Пауза — число секунд, не меньше 10.",
    "automation.keyword_scope.title": "ГДЕ СЛУШАТЬ",
    "automation.keyword_scope.text": (
        "Слова: **{words}**\nБот ответит там же, где их написали (в канале или ветке).\n\n"
        "Чтобы бот видел текст всех сообщений, нужен Message Content Intent (см. README); "
        "без него сработают только сообщения с упоминанием бота."
    ),
    "automation.keyword_scope.here": "Только этот канал",
    "automation.keyword_scope.everywhere": "Весь сервер",
    "automation.trigger_item.toggle": "Пауза / включить",
    "automation.trigger_item.remove": "Удалить",
    "automation.trigger_item.back": "Назад",
    "automation.settings.title": "НАСТРОЙКИ BUILD'А",
    "automation.settings.text": (
        "**Живое обновление:** {live}\n**Родитель стиля:** {parent}\n**Варианты по ролям:**\n{variants}\n\n"
        "**Переменные** для текста и embed'ов:\n`{variables}`"
    ),
    "automation.settings.live_on": "каждые {n} мин",
    "automation.settings.live_off": "выключено (обновление — по событиям и вручную)",
    "automation.settings.no_parent": "нет",
    "automation.settings.no_variants": "нет — всем показывается сам build",
    "automation.settings.pick_parent": "Выбери родителя",
    "automation.settings.live_timer": "Живое обновление",
    "automation.settings.parent": "Родитель стиля",
    "automation.settings.add_variant": "Вариант по роли",
    "automation.settings.clear_variants": "Убрать варианты",
    "automation.live_modal.title": "ЖИВОЕ ОБНОВЛЕНИЕ",
    "automation.live_modal.minutes_input": "Раз в сколько минут (0 — выключить)",
    "automation.live.bad": "Число минут: 0 (выключить) или от {min}.",
    "automation.parent.title": "РОДИТЕЛЬ СТИЛЯ",
    "automation.parent.text": (
        "Этот build возьмёт у родителя цвет, а также author, footer и thumbnail, если свои не заданы. "
        "Поменяешь родителя и нажмёшь у него «Обновить отправленные» — обновятся и все «дети»."
    ),
    "automation.variant.title": "ВАРИАНТ ПО РОЛИ",
    "automation.variant.text": (
        "Когда этот build открывают кнопкой, бот может показать другой build — в зависимости от того, кто нажал. "
        "Например, staff — панель модерации, остальным — кнопку «Подать заявку». Кому показывать вариант?"
    ),
    "automation.variant.staff": "Staff и выше",
    "automation.variant.admin": "Admin и выше",
    "automation.variant.roles": "…или выбери роли",
    "automation.variant.pick_build": "Какой build им показывать",
    "automation.variant.level": "{level}+",
    "automation.variant.line": "{who} → {build}",
    "automation.variant_build.title": "ЧТО ПОКАЗАТЬ",
    "automation.variant_build.text": "Выбери build, который увидят эти люди вместо основного.",
    "actions.build_refresh.done": "🔄 Обновлено сообщений: {updated}.",
    "actions.build_refresh.cooldown": "⏳ Эти сообщения только что обновлялись — попробуй через {seconds} сек.",
    "actions.counter.bad_value": "Счётчик: имя и изменение, например `очки +1`, `очки -5` или `очки =0`.",
    "actions.counter.done": "Счётчик **{name}**: {value}",
    "embed.value_hint.counter.change": "очки +1  ·  очки -1  ·  очки =0",
    "embed.value_hint.build.goto": "ID Message Build",
    "embed.value_hint.build.refresh": "ID Message Build",
    "live.last_submission": "{form} — {user} ({when})",
    "build_tools.import_modal.link_input": "Ссылка на сообщение или его ID",
    "build_tools.import_modal.link_input.placeholder": "ПКМ по сообщению → Копировать ссылку",
    "build_tools.import.bad_ref": "Не поняла, что за сообщение. Вставь ссылку (ПКМ по сообщению → «Копировать ссылку») или ID сообщения из этого канала.",
    "build_tools.import.other_guild": "Это сообщение с другого сервера. Чтобы перенести build между серверами, используй «Экспорт JSON» и `/embed file:`.",
    "build_tools.import.no_channel": "Канал из ссылки не найден на этом сервере.",
    "build_tools.import.no_access": "У тебя нет доступа к истории этого канала.",
    "build_tools.import.bot_no_access": "Бот не видит этот канал или его историю.",
    "build_tools.import.not_found": "Сообщение не найдено — возможно, его удалили.",
    "build_tools.import.empty": "В этом сообщении нечего забирать: нет ни текста, ни embed'ов, ни кнопок.",
    "build_tools.import.name": "Из сообщения {id}",
    "build_tools.import.done": "📥 Собрано из сообщения: embed'ов {embeds}, кнопок {buttons}.",
    "build_tools.import.dropped": "⚠️ Действий сброшено: {count} — роль/форма/build недоступны тебе или не существуют на этом сервере.",
    "build_tools.import.unconfigured": "⚠️ Без действия: {count} — кнопки/опции чужого бота. Убери их и добавь заново с нужным действием.",
    "build_tools.import.save_hint": "Это ещё черновик: «Подтвердить дизайн» → «Сохранить».",
    "build_tools.json.done": "📥 Импортировано из файла: embed'ов {embeds}, кнопок {buttons}.",
    "build_tools.json.exported": "Готово. Этот файл можно загрузить на любом сервере с этим ботом: `/embed file:`.",
    "build_tools.json.too_big": "Файл слишком большой (максимум 512 КБ).",
    "build_tools.json.bad_json": "Это не JSON-файл или он повреждён.",
    "build_tools.json.bad_format": "Это не экспорт Message Build.",
    "build_tools.json.read_error": "Не удалось скачать файл, попробуй ещё раз.",
    "build_tools.versions.title": "ИСТОРИЯ ВЕРСИЙ",
    "build_tools.versions.text": "Перед каждым сохранением бот запоминает, как build выглядел до правки (последние 25 версий). Выбери версию, чтобы посмотреть или откатить.",
    "build_tools.versions.empty": "Версий пока нет — они появятся после первой правки",
    "build_tools.versions.placeholder": "Выбери версию",
    "build_tools.versions.option": "{when} · до правки {who}",
    "build_tools.versions.missing": "Эта версия больше не хранится.",
    "build_tools.version.title": "ВЕРСИЯ",
    "build_tools.version.text": "Сохранена {when}, правку начал(а) {who}.\nНазвание: **{name}**\n\nОткат тоже попадает в историю — его можно отменить.",
    "build_tools.version.preview": "Предпросмотр",
    "build_tools.version.restore": "Откатить к этой версии",
    "build_tools.version.preview_note": "Так выглядела эта версия (кнопок в ней: {buttons}):",
    "build_tools.version.restored": "⏪ Откат выполнен. Уже отправленные сообщения обновятся по кнопке «Обновить отправленные».",
    "embed.default_name": "Новый Message Build",
    "embed.build_not_found": "Message Build не найден.",
    "embed.build_empty": "Этот Message Build пустой.",
    "embed.delete_denied": "Удалить может только создатель.",
    "embed.preview_footer": "Embed {n}/{total} · видимость: {visibility}",

    "embed.saved.title": "СОХРАНЁННЫЕ MESSAGE BUILD",
    "embed.saved.text": "Выбери, чтобы открыть предпросмотр и действия.",
    "embed.saved.empty": "Сохранённых Message Build нет",
    "embed.build_card.title": "MESSAGE BUILD",
    "embed.build_card.text": "ID: `{id}` · автор: {owner}\nВидимость: `{visibility}`\nEmbed'ов: {embeds} · кнопок: {buttons}\nОтправлено сообщений: {sent}",
    "embed.templates.title": "ШАБЛОНЫ",
    "embed.templates.text": "Выбери message-шаблон.",
    "embed.templates.empty": "Шаблонов ещё нет",

    "embed.visibility.title": "ВИДИМОСТЬ",
    "embed.visibility.text": "Кто сможет видеть и использовать это сообщение?",
    "embed.visibility.public": "Публичный",
    "embed.visibility.private": "Приватный",
    "embed.visibility.restricted": "Ограниченный",
    "embed.restriction.title": "ОГРАНИЧЕННЫЙ ДОСТУП",
    "embed.restriction.text": "По уровню доступа или по конкретной роли?",
    "embed.restriction.by_level": "По уровню доступа",
    "embed.restriction.by_role": "По роли(ям)",
    "embed.restriction_level.title": "УРОВЕНЬ",
    "embed.restriction_level.text": "Кто минимум сможет видеть это сообщение?",
    "embed.restriction_level.staff": "Staff",
    "embed.restriction_level.admin": "Admin",
    "embed.restriction_roles.title": "РОЛИ",
    "embed.restriction_roles.text": "Выбери до 5 ролей.",
    "embed.restriction_roles.placeholder": "Выбери роль(и)",

    "embed.switch.placeholder": "Переключить embed",
    "embed.switch.option": "Embed {n}",
    "embed.switch.add": "➕ Добавить embed",
    "embed.editor.basic": "Основное",
    "embed.editor.media": "Изображения",
    "embed.editor.author_footer": "Author/Footer",
    "embed.editor.add_field": "Добавить поле",
    "embed.editor.confirm": "Подтвердить дизайн",
    "embed.editor.too_many_fields": "В одном embed максимум 25 полей.",
    "embed.basic_modal.title": "ОСНОВНОЕ",
    "embed.basic_modal.title_input": "Title",
    "embed.basic_modal.description_input": "Description",
    "embed.basic_modal.color_input": 'Цвет HEX',
    "embed.basic_modal.bad_color": "Некорректный HEX-цвет.",
    "embed.media_modal.title": "ИЗОБРАЖЕНИЯ",
    "embed.media_modal.thumbnail_input": "Thumbnail URL",
    "embed.media_modal.image_input": "Image URL",
    "embed.author_modal.title": "AUTHOR / FOOTER",
    "embed.author_modal.author_input": "Author name",
    "embed.author_modal.footer_input": "Footer",
    "embed.field_modal.title": "ПОЛЕ",
    "embed.field_modal.name_input": "Название",
    "embed.field_modal.value_input": "Значение",
    "embed.field_modal.inline_input": "Inline? yes/no",

    "embed.interactive.title": "ИНТЕРАКТИВ",
    "embed.interactive.text": 'Кнопок: **{buttons}/{max}**\n{extra}\n\nДобавь кнопки, список или кнопку формы — всё можно сочетать. Потом «Сохранить».',

    "embed.list.title": "ОТКРЫВАЮЩИЙСЯ СПИСОК",
    "embed.list.text": 'Опций: **{count}/25**\n\n{options}',
    "embed.list.add_option": "Добавить опцию",
    "embed.list.too_many": "Максимум 25 опций в select.",
    "embed.list.placeholder": "Выбери опцию",
    "embed.list.default_option": "Опция",
    "embed.list.option_missing": "Опция не найдена.",
    "embed.list_option_modal.title": "ОПЦИЯ СПИСКА",
    "embed.list_option_modal.label_input": "Текст опции",
    "embed.list_option_modal.description_input": "Описание",
    "embed.list_option_modal.emoji_input": "Emoji",
    "embed.list_value_modal.title": "ЗНАЧЕНИЕ ОПЦИИ",
    "embed.list_value_modal.value_input": "Текст ответа при выборе",
    "embed.pick_action": "Выбери действие",
    "embed.no_actions": "Нет доступных действий",
    "embed.no_actions_allowed": "Тебе не разрешено ни одно действие из реестра.",

    "embed.native_select.title": "ВЫБОР",
    "embed.native_select.text": "Какой тип выбора нужен?",
    "embed.native_select.role": "Роль",
    "embed.native_select.user": "Участник",
    "embed.native_select.channel": "Канал",
    "embed.native_select.mentionable": "Mentionable",

    "embed.buttons.title": "КНОПКИ",
    "embed.buttons.text": 'Кнопок: **{count}/{max}**\n\n{buttons}',
    "embed.buttons.added": "Добавлено: {count}/{max}.",
    "embed.buttons.add": "Добавить кнопку",
    "embed.buttons.too_many": 'Максимум {max} кнопок.',
    "embed.button_label_modal.title": "ТЕКСТ КНОПКИ",
    "embed.button_label_modal.label_input": "Текст кнопки",
    "embed.button_color.title": "ЦВЕТ КНОПКИ",
    "embed.button_color.text": "Выбери стиль (Discord поддерживает только эти 5, кастомный HEX недоступен).",
    "embed.button_color.blue": "🔵 Синяя",
    "embed.button_color.grey": "⚪ Серая",
    "embed.button_color.green": "🟢 Зелёная",
    "embed.button_color.red": "🔴 Красная",
    "embed.button_color.link": "🔗 Ссылка",
    "embed.button_action.title": "ДЕЙСТВИЕ",
    "embed.button_action.text": "Что должна делать кнопка? Список зависит от твоего уровня доступа.",
    "embed.build_pick.title": "СООБЩЕНИЕ ДЛЯ КНОПКИ",
    "embed.build_pick.text": (
        "Выбери сохранённый Message Build. По нажатию участник увидит его (только для себя) "
        "вместе со всеми кнопками и списками, которые в нём были. Правки build'а подхватываются сразу."
    ),
    "embed.build_pick.placeholder": "Выбери сохранённое сообщение",
    "embed.build_pick.option": "Видимость: {visibility}",
    "embed.build_pick.none": "Сначала сохрани сообщение в /embed — потом его можно прикрепить к кнопке.",
    "embed.button_value_modal.title": "ЗНАЧЕНИЕ",
    "embed.button_value_modal.value_input": "URL или текст действия",

    "embed.saved_build.title": "MESSAGE BUILD СОХРАНЁН",
    "embed.saved_build.text": "ID: `{id}` · embed'ов: {embeds} · кнопок: {buttons}",
    "embed.final.preview": "Предпросмотр",
    "embed.final.send": "Отправить",
    "embed.final.save_template_button": "Сохранить как шаблон",
    "embed.final.delete": "Удалить",
    "embed.deleted.title": "MESSAGE BUILD УДАЛЁН",
    "embed.send.placeholder": "Куда отправить",
    "embed.send.prompt": "Выбери канал(ы):",
    "embed.send.sent": "Отправлено: {channels}",
    "embed.send.failed": "Не удалось:\n{errors}",
    "embed.send.channel_missing": "{channel} — канал не найден",
    "embed.send.forbidden": "{channel} — нет прав на отправку",
    "embed.send.http_error": "{channel} — ошибка Discord: `{error}`",
    "embed.save_template_modal.title": "СОХРАНИТЬ КАК ШАБЛОН",
    "embed.save_template_modal.name_input": "Название шаблона",
    "embed.save_template_modal.category_input": "Категория",
    "embed.save_template_modal.done": "Сохранено как шаблон `{id}`.",

    # ================= /buttons =================
    "buttons.home.title": "BUTTON BUILDER",
    "buttons.home.text": "Отдельные наборы кнопок без embed'а: собери до {max} кнопок и опубликуй в канал. Если нужен красивый пост с кнопками — используй /embed.",
    "buttons.home.create": "Создать набор",
    "buttons.home.saved": "Сохранённые наборы",
    "buttons.default_name": "Новый набор кнопок",
    "buttons.builder.title": "BUTTON BUILDER",
    "buttons.builder.text": '**{name}**\nМожно добавить до {max} кнопок.\n\n{buttons}',
    "buttons.builder.line": "{n}. {emoji} {label} · {action}",
    "buttons.builder.empty": "Кнопок пока нет.",
    "buttons.builder.need_button": "Добавь хотя бы одну кнопку.",
    "buttons.builder.add": "Добавить кнопку",
    "buttons.builder.done": "Готово",
    "buttons.builder.clear": "Очистить",
    "buttons.limit": "Лимит достигнут: максимум {max} кнопок.",
    "buttons.modal.title": "НОВАЯ КНОПКА",
    "buttons.modal.label_input": "Текст кнопки",
    "buttons.modal.emoji_input": "Emoji",
    "buttons.modal.emoji_input.placeholder": "Например: ✨ или :my_emoji:",
    "buttons.modal.style_input": "Стиль: primary / secondary / success / danger",
    "buttons.modal.action_input": 'Действие: link / message / confirm / build',
    "buttons.modal.value_input": "URL, текст или ID build'а из /messages",
    "buttons.modal.bad_style": "Стиль должен быть: primary, secondary, success или danger.",
    "buttons.modal.bad_action": 'Такого действия нет или оно тебе недоступно. Варианты: link, message, confirm, build (сохранённое сообщение) или ключ из реестра действий.',
    "buttons.modal.need_url": "Для link нужен URL.",
    "buttons.saved_set.title": "BUTTON SET СОХРАНЁН",
    "buttons.saved_set.text": "ID: `{id}`\nКнопок: **{count}**",
    "buttons.list.title": "BUTTON SETS",
    "buttons.list.text": "Выберите сохранённый набор.",
    "buttons.list.empty": "Сохранённых наборов нет",
    "buttons.not_found": "Набор не найден.",
    "buttons.card.title": "НАБОР КНОПОК",
    "buttons.card.text": "Категория: `{category}`\nВидимость: `{visibility}`\nКнопок: `{count}`",

    # ================= /forms =================
    "forms.home.title": "FORM BUILDER",
    "forms.home.text": "Создание форм, приватных заявок, reviewers и действий после решения.",
    "forms.start.create": "Создать",
    "forms.start.saved": "Сохранённые",
    "forms.default_name": "Новая форма",
    "forms.builder.title": "FORM BUILDER",
    "forms.builder.text": '**Название:** {name}\n**Категория:** {category}\n**Видимость:** {visibility}\n**Канал заявок:** {destination}\n**Reviewers:** {reviewer_roles} ролей / {reviewer_users} пользователей\n**После решения:** {post_action}\n**Роль после одобрения:** {post_role}\n**Уведомлять заявителя в ЛС:** {dm}\n\n**Вопросы:**\n{questions}',
    "forms.builder.question_line": "{n}. {label} · {type} · {required}",
    "forms.builder.no_questions": "нет",
    "forms.builder.channel_unset": "не задан",
    "forms.builder.role_unset": "не задана",
    "forms.builder.need_question": "Нужны хотя бы один вопрос и канал заявок.",
    "forms.builder.basic": "Основные",
    "forms.builder.question": "Вопрос",
    "forms.builder.routing": "Маршрутизация",
    "forms.builder.target": "Роль для заявки",
    "forms.builder.save": "Сохранить",
    "forms.question.required": "required",
    "forms.question.optional": "optional",
    "forms.basic_modal.title": "ОСНОВНЫЕ ДАННЫЕ ФОРМЫ",
    "forms.basic_modal.name": "Название",
    "forms.basic_modal.description": "Описание",
    "forms.basic_modal.category": "Категория",
    "forms.basic_modal.visibility": "private/public",
    "forms.basic_modal.roles": "Разрешённые role ID через запятую",
    "forms.basic_modal.bad_visibility": "Видимость: private или public.",
    "forms.question_modal.title": "ВОПРОС ФОРМЫ",
    "forms.question_modal.label": 'Вопрос (до 45 символов)',
    "forms.question_modal.qtype": "short / long / yesno",
    "forms.question_modal.required": "required? yes/no",
    "forms.question_modal.bad_type": "Тип: short, long или yesno.",
    "forms.question_modal.too_many": "Максимум {max} вопросов для одного Discord Modal.",
    "forms.routing_modal.title": "МАРШРУТИЗАЦИЯ ФОРМЫ",
    "forms.routing_modal.destination": "ID канала заявок",
    "forms.routing_modal.reviewer_roles": "Reviewer role IDs через запятую",
    "forms.routing_modal.reviewer_users": "Reviewer user IDs через запятую",
    "forms.routing_modal.action": "review / role / none",
    "forms.routing_modal.role": "Role ID после одобрения",
    "forms.routing_modal.invalid": "Проверь ID канала и действие.",
    "forms.target_role.title": "TARGET ROLE",
    "forms.target_role.text": "Выберите роль, на которую человек подаёт заявку.",
    "forms.target_role.placeholder": "Роль, на которую подаётся заявка",
    "forms.saved.title": "ФОРМА СОХРАНЕНА",
    "forms.saved.text": "ID: `{id}`\nКанал заявок: {channel}\nРоль: {role}",
    "forms.use.apply": "Подать заявку",
    "forms.not_found": "Форма не найдена.",
    "forms.unavailable": "Форма недоступна.",
    "forms.no_description": "Без описания",
    "forms.card.title": "ФОРМА",
    "forms.list.title": "FORMS",
    "forms.list.text": "Выберите форму.",
    "forms.list.empty": "Форм пока нет",
    "forms.submitted": "РЕПЛИКА ОС — заявка отправлена приватно. Reviewers получат её в настроенном канале.",
    "forms.submission.title": "НОВАЯ ЗАЯВКА",
    "forms.submission.text": "Форма: **{form}**\nЗаявитель: {user}\nID: `{id}`",
    "forms.review.approve": "Одобрить",
    "forms.review.reject": "Отклонить",
    "forms.review.not_found": "Заявка не найдена.",
    "forms.review.no_rights": "У вас нет права рассматривать эту заявку.",
    "forms.review.already": "Уже обработано: {status}.",
    "forms.review.role_forbidden": "Discord не разрешил выдать роль. Проверь права бота и иерархию ролей.",
    "forms.review.role_missing": "Не удалось найти участника или роль для назначения.",
    "forms.reviewed.title": "ЗАЯВКА ОБРАБОТАНА",
    "forms.reviewed.text": "Статус: **{status}**\nReviewer: {reviewer}",
    "forms.status.pending": "pending",
    "forms.status.approved": "approved",
    "forms.status.rejected": "rejected",

    # ================= /templates =================
    "templates.home.title": "TEMPLATE MANAGER",
    "templates.home.text": 'Библиотека готовых заготовок сообщений: сохранила один раз — используешь сколько угодно. Можно делиться с ролями и добавлять в избранное.',
    "templates.home.list": "Список",
    "templates.home.save": "Сохранить JSON",
    "templates.list.title": "ШАБЛОНЫ",
    "templates.list.text": "Доступные вам шаблоны.",
    "templates.list.empty": "Шаблонов нет",
    "templates.card.title": "ШАБЛОН",
    "templates.card.text": "Type: `{type}`\nCategory: `{category}`\nVisibility: `{visibility}`\nИзбранное: **{favorite}**",
    "templates.card.use": "Использовать",
    "templates.card.favorite": "Избранное",
    "templates.card.delete": "Удалить",
    "templates.button_set.title": "НАБОР КНОПОК",
    "templates.deleted.title": "ШАБЛОН УДАЛЁН",
    "templates.not_found": "Шаблон не найден.",
    "templates.unavailable": "Шаблон недоступен.",
    "templates.empty": "Этот шаблон пустой и не может быть показан.",
    "templates.form_hint": "Для формы используй сохранённый Form ID в payload.",
    "templates.delete_denied": "Удалять может создатель или владелец.",
    "templates.modal.title": "СОХРАНИТЬ ШАБЛОН",
    "templates.modal.name": "Название",
    "templates.modal.typ": "message / buttons / form",
    "templates.modal.category_visibility": "Категория/видимость (general/public)",
    "templates.modal.roles": "Role IDs через запятую",
    "templates.modal.payload": "JSON payload",
    "templates.modal.bad_type": "Проверь тип и поле `категория/private` или `категория/public`.",
    "templates.modal.bad_json": "JSON некорректен.",
    "templates.modal.saved": "Шаблон сохранён: `{id}`",

    # ================= /webhooks =================
    "webhooks.home.title": "WEBHOOK MANAGER",
    "webhooks.home.text": 'Вебхуки — сообщения от имени «другого бота» со своим именем и аватаркой. Здесь их можно создать, настроить и отправлять через них.',
    "webhooks.home.create": "Создать",
    "webhooks.home.list": "Список",
    "webhooks.home.history": "История",
    "webhooks.create_modal.title": "СОЗДАТЬ WEBHOOK",
    "webhooks.create_modal.name": "Название",
    "webhooks.create_modal.avatar": "Avatar URL",
    "webhooks.pick_channel": "Выберите канал.",
    "webhooks.channel_placeholder": "Канал",
    "webhooks.need_manage": "Нужны права Manage Webhooks.",
    "webhooks.discord_error": "Ошибка Discord: `{error}`",
    "webhooks.error": "Ошибка: `{error}`",
    "webhooks.created.title": "WEBHOOK СОЗДАН",
    "webhooks.created.text": "Канал: {channel}\nИмя: **{name}**\nID: `{id}`\n\n🔒 URL скрыт.",
    "webhooks.list.title": "WEBHOOKS",
    "webhooks.list.text": "Сохранённые webhook. URL скрыты.",
    "webhooks.list.empty": "Webhook нет",
    "webhooks.not_found": "Webhook не найден.",
    "webhooks.card.title": "WEBHOOK",
    "webhooks.card.text": "Имя: **{name}**\nКанал: {channel}\nID: `{id}`\n\n🔒 URL скрыт.",
    "webhooks.card.show": "Показать URL",
    "webhooks.card.send": "Отправить",
    "webhooks.card.rename": "Переименовать",
    "webhooks.card.avatar": "Аватар",
    "webhooks.card.test": "Тест",
    "webhooks.card.history": "История",
    "webhooks.card.delete": "Удалить",
    "webhooks.card.regenerate": "Пересоздать URL",
    "webhooks.access_denied": "Доступ запрещён.",
    "webhooks.url": "🔑 `{url}`\n\nНе публикуй этот URL.",
    "webhooks.test_message": "Webhook Manager · тестовое сообщение.",
    "webhooks.test_sent": "Тест отправлен.",
    "webhooks.history.title": "WEBHOOK HISTORY",
    "webhooks.history.empty": "История пуста.",
    "webhooks.delete.confirm": "⚠️ Webhook будет удалён. Подтвердить?",
    "webhooks.delete.yes": "Удалить",
    "webhooks.delete.done": "Webhook удалён. Старый URL больше не работает.",
    "webhooks.regenerate.owner_only": "Пересоздавать URL может только владелец.",
    "webhooks.regenerate.confirm": "⚠️ Старый URL перестанет работать. Подтвердить?",
    "webhooks.regenerate.yes": "Да, пересоздать",
    "webhooks.regenerate.done": "♻️ URL пересоздан. Старый URL больше не работает.",
    "webhooks.message_modal.title": "WEBHOOK MESSAGE",
    "webhooks.message_modal.text": "Текст",
    "webhooks.message_modal.embed_title": "Embed title",
    "webhooks.message_modal.description": "Embed description",
    "webhooks.message_modal.image": "Image URL",
    "webhooks.message_modal.thumbnail": "Thumbnail URL",
    "webhooks.message_modal.empty": "Добавь текст или данные для embed.",
    "webhooks.message_modal.sent": "Отправлено через webhook.",
    "webhooks.rename_modal.title": "ПЕРЕИМЕНОВАТЬ WEBHOOK",
    "webhooks.rename_modal.name": "Новое имя",
    "webhooks.rename_modal.done": "Имя изменено.",
    "webhooks.avatar_modal.title": "ИЗМЕНИТЬ АВАТАР",
    "webhooks.avatar_modal.avatar": "Прямая URL-ссылка",
    "webhooks.avatar_modal.fetch_failed": "Не удалось получить изображение.",
    "webhooks.avatar_modal.done": "Аватар изменён.",

    # ================= /select =================
    "select.home.title": 'МЕНЮ РОЛЕЙ',
    "select.home.text": 'Меню ролей: участники сами выбирают себе роли из списка, который ты задашь. Роли с админскими правами добавить нельзя.',
    "select.picked": "Выбрано: {value}",

    # ================= /messages =================
    "messages.home.title": "MESSAGE MANAGER",
    "messages.home.text": 'Все сохранённые сообщения (Message Build), которые тебе доступны. Выбери одно, чтобы посмотреть, отправить, изменить или настроить автоматику.',

    # ================= /panel (веб-панель) =================
    "panel.link": "Ссылка на веб-панель. Одноразовая, действует 10 минут — никому не пересылай.",
    "panel.open": "Открыть панель",
    "panel.disabled": (
        "Веб-панель не настроена: добавь в .env `WEB_PANEL_PORT` (порт из вкладки Network) "
        "и `WEB_PANEL_URL` (например `http://1.2.3.4:25565`), затем перезапусти бота."
    ),

    # ================= ДОБАВЛЕНО ПРИ АУДИТЕ: роли, логотипы, меню ролей и т.д. =================
    "common.error": 'РЕПЛИКА ОС — что-то пошло не так. Ошибка записана в лог, попробуй ещё раз.',
    "ping.reply_latency": '🏓 Pong! {ms} мс',
    "roles.not_found": 'Роль не найдена.',
    "roles.everyone": '@everyone нельзя выдавать.',
    "roles.managed": 'Эта роль управляется интеграцией — её нельзя выдавать или менять.',
    "roles.above_bot": 'Роль выше или наравне с ролью бота — подними роль бота в настройках сервера.',
    "roles.above_actor": 'Роль выше или наравне с твоей самой высокой ролью.',
    "roles.dangerous": 'У роли опасные права (админ, баны, управление сервером и т.п.) — раздавать её через бота может только владелец.',
    "actions.source_gone": 'Эта кнопка устарела: её источник удалён.',
    "actions.creator_revoked": 'Создатель этой кнопки больше не имеет права на это действие.',
    "actions.edit_not_bot": 'Редактировать можно только сообщения бота.',
    "actions.webhook_record_missing": 'Вебхук не найден на этом сервере.',
    "actions.build_no_access": 'Это сообщение тебе недоступно: оно ограничено по ролям/уровню или его автор потерял к нему доступ.',
    "actions.bad_value.link": 'Нужна ссылка вида https://…',
    "embed.value_hint.link": 'https://example.com',
    "embed.value_hint.message.send": 'Текст, который увидит нажавший',
    "embed.value_hint.message.confirm": 'Текст подтверждения',
    "embed.value_hint.form.trigger": 'ID формы, например 12',
    "embed.value_hint.select.trigger": 'role / user / channel / mentionable',
    "embed.value_hint.role.assign": 'ID роли или @упоминание роли',
    "embed.value_hint.role.remove": 'ID роли или @упоминание роли',
    "embed.value_hint.role.toggle": 'ID роли или @упоминание роли',
    "embed.value_hint.webhook.send": 'ID вебхука из /webhooks или URL',
    "embed.value_hint.build.trigger": 'ID Message Build (виден в /messages, например 12)',
    "access.home.audit_button": 'Журнал',
    "access.audit.title": 'ЖУРНАЛ ДЕЙСТВИЙ',
    "access.audit.text": 'Последние действия на сервере:\n\n{entries}',
    "access.audit.line": '{time} · {actor} · `{action}` {target} {details}',
    "access.audit.empty": 'Журнал пуст.',
    "access.registry.line": '{status} `{key}` — создаёт: {create} · жмёт: {use} {danger}',
    "access.action.toggle_dangerous": 'Подтверждение вкл/выкл',
    "access.action.use_member": 'Жмёт: Member',
    "access.action.use_staff": 'Жмёт: Staff',
    "access.action.use_admin": 'Жмёт: Admin',
    "access.settings.backup_too_large": 'Файл больше лимита загрузки Discord.',
    "buttons.builder.rename": 'Название',
    "buttons.name_modal.title": 'НАЗВАНИЕ НАБОРА',
    "buttons.name_modal.name_input": 'Название',
    "buttons.name_modal.visibility_input": 'private / public',
    "buttons.actions.preview": 'Предпросмотр',
    "buttons.actions.publish": 'Опубликовать',
    "buttons.actions.delete": 'Удалить',
    "buttons.deleted.title": 'НАБОР УДАЛЁН',
    "buttons.public_card.title": '',
    "embed.bad_emoji": 'Emoji не распознан: используй символ эмодзи или <:name:id>.',
    "embed.edit_denied": 'Изменять этот Message Build может только его автор или администратор.',
    "embed.preview_error": 'Discord не принял сообщение: `{error}`',
    "embed.editor.no_fields": 'У этого embed нет полей.',
    "embed.editor.meta": 'Название и текст',
    "embed.editor.timestamp": 'Время',
    "embed.editor.delete_embed": 'Удалить embed',
    "embed.editor.last_embed": 'Это единственный embed. Если нужно сообщение без embed\'а — просто оставь его пустым: пустые embed\'ы не отправляются.',
    "embed.editor.visibility": 'Видимость',
    "embed.editor.fields_placeholder": 'Изменить или удалить поле…',
    "embed.editor.field_option": '{n}. {name}',
    "embed.preview_empty": 'пустой — не отправится',
    "embed.field_modal.empty": 'Заполни название или значение поля.',
    "embed.field_modal.delete_hint": 'Очисти оба поля, чтобы удалить',
    "embed.bad_url": 'Поле «{field}»: `{value}` — не похоже на ссылку. Нужен адрес вида https://site.com/картинка.png',
    "embed.too_long": 'Embed получится {length} символов, а Discord принимает максимум {max}. Сократи текст или поля.',
    "embed.too_long_n": 'Embed {n}: {length} символов, а Discord принимает максимум {max}. Сократи его перед сохранением.',
    "embed.save_empty": 'Сообщение пустое: добавь текст, заполни embed или добавь кнопки.',
    "embed.buttons.remove_placeholder": 'Убрать кнопку…',
    "embed.list.remove_placeholder": 'Убрать опцию…',
    "embed.basic_modal.url_input": 'URL заголовка',
    "embed.author_modal.author_url_input": 'Author URL',
    "embed.author_modal.author_icon_input": 'Author icon URL',
    "embed.author_modal.footer_icon_input": 'Footer icon URL',
    "embed.meta_modal.title": 'НАЗВАНИЕ И ТЕКСТ',
    "embed.meta_modal.name_input": "Название build'а",
    "embed.meta_modal.content_input": "Текст над embed'ами",
    "embed.meta_modal.category_input": 'Категория',
    "embed.button_label_modal.emoji_input": 'Emoji',
    "embed.button_label_modal.emoji_input.placeholder": '✨ или <:name:id>',
    "embed.restriction_level.member": 'Member',
    "embed.interactive.buttons": 'Кнопки',
    "embed.interactive.list": 'Список',
    "embed.interactive.native": 'Выбор роли/участника',
    "embed.interactive.form": 'Кнопка формы',
    "embed.interactive.save": 'Сохранить',
    "embed.interactive.send_now": 'Отправить',
    "embed.send_pick.title": "КУДА ОТПРАВИТЬ",
    "embed.send_pick.text": "Выбери до 5 каналов, веток или форумов. После отправки спрошу, сохранить ли сообщение в «Мои сохранённые».",
    "embed.send_failed.title": "НЕ ОТПРАВЛЕНО",
    "embed.send_failed.text": "{result}\n\nСообщение не сохранено. Вернись назад, чтобы выбрать другой канал.",
    "embed.sent_saved.title": "ОТПРАВЛЕНО",
    "embed.sent_saved.text": "{result}\n\nИзменения сохранены в Message Build `{id}`.",
    "embed.save_after.title": "ОТПРАВЛЕНО",
    "embed.save_after.text": (
        "{result}\n\nДобавить сообщение в «Мои сохранённые»? Сохранённое можно потом править, "
        "отправлять снова, ставить в расписание. Кнопки в отправленном работают в любом случае."
    ),
    "embed.save_after.save": "Сохранить",
    "embed.save_after.skip": "Не нужно",
    "embed.save_after_skipped.title": "ГОТОВО",
    "embed.save_after_skipped.text": "Сообщение отправлено и работает. В списке сохранённых его не будет.",
    "embed.save_after_modal.title": "СОХРАНИТЬ СООБЩЕНИЕ",
    "embed.save_after_modal.name_input": "Название в списке",
    "embed.interactive.clear_interactive": 'Убрать список',
    "embed.interactive.summary_list": 'Список: **{count}** опций',
    "embed.interactive.summary_native": 'Выбор: **{kind}**',
    "embed.interactive.summary_none": 'Списка нет',
    "embed.list.empty": 'Опций пока нет.',
    "embed.list.remove_last": 'Убрать последнюю',
    "embed.buttons.remove_last": 'Убрать последнюю',
    "embed.form_attach.title": 'КНОПКА ФОРМЫ',
    "embed.form_attach.text": 'Выбери форму — в сообщение добавится кнопка «Подать заявку».',
    "embed.form_attach.placeholder": 'Форма',
    "embed.form_attach.empty": 'Доступных форм нет',
    "embed.final.edit": 'Редактировать',
    "embed.final.resync": 'Обновить отправленные',
    "embed.saved_build.updated": "Изменения сохранены. ID: `{id}` · embed'ов: {embeds} · кнопок: {buttons}\nОтправленных сообщений: {sent} — нажми «Обновить отправленные», чтобы применить правки к ним.",
    "embed.resync.done": 'Обновлено: {updated} · удалено лишних: {removed} · дослано: {added} · не найдено: {missing}',
    "embed.resync.none": 'Этот Message Build ещё никуда не отправлялся.',
    "embed.send.no_perm_user": '{channel} — у тебя нет права писать в этот канал',
    "embed.send.no_perm_bot": '{channel} — у бота нет права писать сюда или вставлять ссылки',
    "forms.builder.need_role": 'Для действия «role» укажи роль после одобрения или роль для заявки.',
    "forms.builder.remove_question": 'Убрать вопрос',
    "forms.builder.toggle_dm": 'Уведомлять в ЛС',
    "forms.routing_modal.bot_cannot_post": 'Бот не может писать в {channel} — дай ему права на отправку и ссылки.',
    "forms.use.publish": 'Опубликовать',
    "forms.use.delete": 'Удалить форму',
    "forms.public_card.title": 'ЗАЯВКА',
    "forms.published": 'Опубликовано в {channel}.',
    "forms.deleted.title": 'ФОРМА УДАЛЕНА',
    "forms.manage_denied": 'Управлять этим может только создатель или администратор.',
    "forms.already_pending": 'У тебя уже есть заявка по этой форме — дождись решения.',
    "forms.destination_missing": 'Канал заявок этой формы недоступен — сообщи администратору.',
    "forms.yesno_placeholder": 'да / нет',
    "forms.yesno_invalid": 'На вопрос «{question}» ответь «да» или «нет».',
    "forms.reject_modal.title": 'ПРИЧИНА ОТКАЗА',
    "forms.reject_modal.reason": 'Причина (увидит заявитель)',
    "forms.reviewed.reason": 'Причина: {reason}',
    "forms.status.failed": 'failed',
    "forms.dm.approved": '✅ Твоя заявка «{form}» на сервере {guild} одобрена.',
    "forms.dm.rejected": '❌ Твоя заявка «{form}» на сервере {guild} отклонена.\nПричина: {reason}',
    "forms.dm.no_reason": 'не указана',
    "templates.card.to_editor": 'В редактор',
    "templates.editor_unavailable": 'В редактор можно открыть только message-шаблон, и нужен доступ к /embed.',
    "templates.modal.bad_form": 'Для типа form в JSON нужен существующий "form_id".',
    "webhooks.need_user_manage": 'У тебя нет права Manage Webhooks в этом канале.',
    "select.home.create_menu": 'Создать меню ролей',
    "select.home.menus": 'Мои меню',
    "select.menu_new.title": 'НОВОЕ МЕНЮ РОЛЕЙ',
    "select.menu_new.text": 'Выбери до 25 ролей, которые участники смогут брать себе сами.',
    "select.menu_pick_roles": 'Роли для меню',
    "select.menu_bad_roles": 'Эти роли нельзя добавить в меню:\n{roles}',
    "select.menu_modal.title": 'МЕНЮ РОЛЕЙ',
    "select.menu_modal.name": 'Название меню',
    "select.menu_modal.placeholder": 'Подсказка в списке',
    "select.menu_modal.max_values": 'Сколько ролей можно выбрать',
    "select.menu_card.title": 'МЕНЮ РОЛЕЙ',
    "select.menu_card.text": 'ID: `{id}`\nРоли: {roles}\nМожно выбрать: **{max}**',
    "select.menu_actions.publish": 'Опубликовать',
    "select.menu_actions.delete": 'Удалить',
    "select.menu_deleted.title": 'МЕНЮ УДАЛЕНО',
    "select.menus.title": 'МЕНЮ РОЛЕЙ',
    "select.menus.text": 'Меню, которыми ты можешь управлять.',
    "select.menus_empty": 'Меню пока нет',
    "select.menu_placeholder": 'Выбери роли',
    "select.public_menu.title": '',
    "select.public_menu.text": 'Выбери роли в списке ниже — снятые галочки уберут роль.',
    "select.menu_result": 'Добавлено: {added}\nСнято: {removed}{skipped}',
    "select.menu_skipped": '\nНе удалось: {roles}',
    "logo.no_packages": 'Генератор не установлен: на сервере нужны пакеты huggingface_hub и Pillow (pip install -r requirements.txt).',
    "logo.no_token": 'Генератор не настроен: добавь HF_TOKEN в .env и перезапусти бота.',
    "logo.no_image": 'Прикрепи картинку.',
    "logo.bad_image": 'Нужна картинка PNG, JPG или WEBP (или zip с ними).',
    "logo.image_too_large": 'Файл слишком большой.',
    "logo.no_style": 'без стиля',
    "logo.default_model": 'по умолчанию',
    "logo.rate_limited": 'Лимит генераций: {limit} в час. Попробуй позже.',
    "logo.failed": 'Нейросеть не справилась: `{error}`',
    "logo.no_references": 'В стиле пока нет референсов — добавь их через /logo reference.',
    "logo.style_missing": 'Стиль не найден.',
    "logo.no_role_icons": 'На сервере недоступны иконки ролей — нужен 2 уровень буста.',
    "logo.need_manage_roles": 'Нужно право Manage Roles, чтобы менять иконки ролей.',
    "logo.references_added": 'Референсов добавлено: {added}, пропущено: {skipped}. Всего в стиле: {total}/{max}.',
    "logo.dataset_ready": 'Датасет для обучения LoRA. Триггер-слово стиля: `{trigger}`. Инструкция — в README внутри архива.',
    "logo.dataset_readme": 'Датасет иконок для обучения LoRA (FLUX.1-dev).\n1. Загрузи архив в тренер LoRA (например, fal-ai flux-lora-fast-training или AutoTrain на Hugging Face).\n2. Триггер-слово: {trigger}. Подписи уже лежат рядом с картинками (*.txt).\n3. Опубликуй готовую LoRA как репозиторий на Hugging Face и впиши его в стиль в поле LoRA (/logo styles -> Изменить).\nТогда «С нуля» будет рисовать строго в твоём стиле.',
    "logo.mode.generate": 'с нуля',
    "logo.mode.stylize": 'из макета',
    "logo.mode.nobg": 'без фона',
    "logo.result.title": 'ИКОНКА ГОТОВА',
    "logo.result.text": 'Стиль: **{style}** · режим: {mode}\nТЗ: {brief}',
    "logo.result.apply": 'Поставить на роль',
    "logo.result.again": 'Ещё вариант',
    "logo.result.nobg": 'Убрать фон',
    "logo.result.gone": 'Файл этой иконки больше недоступен.',
    "logo.result.not_yours": 'Это не твоя генерация.',
    "logo.apply.prompt": 'Куда поставить иконку? Подходящие по названию роли — кнопками, или выбери любую в списке.',
    "logo.apply.placeholder": 'Роль',
    "logo.apply.done": 'Иконка установлена на {role}.',
    "logo.apply.failed": 'Discord не принял иконку: `{error}`',
    "logo.apply.too_large": 'Не удалось ужать иконку до 256 КБ.',
    "logo.styles.title": 'СТИЛИ ИКОНОК',
    "logo.styles.text": 'Стиль = описание + референсы (+ LoRA для точного попадания).\nРеференсы: /logo reference (картинка или zip до 60 иконок).\nГенерация: /logo generate (с нуля) и /logo stylize (из макета).',
    "logo.styles.create": 'Новый стиль',
    "logo.style_card.title": 'СТИЛЬ',
    "logo.style_card.text": 'ID: `{id}` · по умолчанию: {default}\nРеференсов: **{refs}**\nМодель: `{model}` · LoRA: `{lora}`\n\n**Описание:** {prompt}\n**Избегать:** {negative}',
    "logo.style_actions.edit": 'Изменить',
    "logo.style_actions.make_default": 'По умолчанию',
    "logo.style_actions.describe": 'Описать по референсам',
    "logo.style_actions.dataset": 'Датасет для LoRA',
    "logo.style_actions.delete": 'Удалить',
    "logo.style_deleted.title": 'СТИЛЬ УДАЛЁН',
    "logo.style_modal.title": 'СТИЛЬ ИКОНОК',
    "logo.style_modal.name": 'Название стиля',
    "logo.style_modal.prompt": 'Описание стиля (для нейросети)',
    "logo.style_modal.negative": 'Чего избегать',
    "logo.style_modal.lora": 'LoRA (репозиторий HF), если есть',
    "logo.style_modal.model": 'Своя модель text-to-image',
    "logo.prompt.base": 'Discord role icon, single centered emblem, bold simple shapes, readable at 32px, plain background, no text, no letters',
    "logo.prompt.default_style": 'clean flat vector icon',
    "logo.prompt.generate": '{brief}. Style: {style}. {base}',
    "logo.prompt.stylize": 'Redraw this icon keeping its subject, silhouette and composition, in this style: {style}. {brief}. {base}',
    "logo.prompt.negative": 'text, watermark, signature, photo, blurry, multiple objects, frame',
    "logo.prompt.describe": 'These images are icons drawn in one consistent style. Describe that style as a short prompt for an image generator (max 60 words): palette, line weight, shading, shapes, materials, background, mood. Do not describe what the icons depict. Answer with the prompt only.',

    "embed.native_select.placeholder": "Выбери...",
    "embed.list.done": "Готово",
    "embed.buttons.done": "Готово",

    # ================= /design =================
    "design.title": "DESIGN",
    "design.text": (
        "Настройки оформления бота.\n\n"
        "Основной цвет: `{embed_color}`\nОпасный цвет: `{danger_color}`\n"
        "Отказ в доступе: {text_access_denied}\nНазад: {nav_back}\nОтмена: {nav_cancel}"
    ),
    "design.edit": "Изменить",
    "design.preview": "Предпросмотр",
    "design.reset": "Сбросить",
    "design.bad_color": "Цвета должны быть в формате `#RRGGBB`.",
    "design.modal.title": "DESIGN SETTINGS",
    "design.modal.embed_color_input": "Основной HEX цвет",
    "design.modal.danger_color_input": "Опасный HEX цвет",
    "design.modal.denied_input": "Текст отказа",
    "design.modal.back_input": "Текст кнопки Назад",
    "design.modal.cancel_input": "Текст кнопки Отмена",

    # ================= ПОЯСНЕНИЯ К КНОПКАМ =================
    # <экран>.<кнопка>.hint — строка под текстом панели. Пусто = не показывать.
    "hints.header": "**Кнопки:**",
    "hints.line": "▸ **{label}** — {hint}",
    "access.home.users_button.hint": 'уровень доступа конкретного человека',
    "access.home.commands_button.hint": 'кто может пользоваться каждой командой',
    "access.home.role_access_button.hint": 'уровень для всех, у кого есть роль',
    "access.home.denials_button.hint": 'запретить человеку пользоваться ботом',
    "access.home.audit_button.hint": 'кто, что и когда менял',
    "access.home.settings_button.hint": 'бэкап, реестр действий кнопок (только владелец)',
    "access.user.limited_button.hint": 'почти ничего не может',
    "access.user.member_button.hint": 'обычные возможности',
    "access.user.staff_button.hint": 'модераторы: формы, кнопки с ролями, автоматика',
    "access.user.admin_button.hint": 'всё, кроме выдачи админки (только владелец)',
    "access.command.add_user.hint": 'дать человеку доступ к команде в обход уровня',
    "access.command.remove_user.hint": 'забрать такой доступ',
    "access.role.remove.hint": 'снять уровень с роли',
    "access.settings.backup.hint": 'прислать копию базы бота файлом',
    "access.settings.denials.hint": 'список запрещённых',
    "access.settings.registry.hint": 'какие действия можно вешать на кнопки и кто их нажимает',
    "access.settings.restart.hint": 'остановить бота, чтобы хостинг запустил его заново',
    "access.action.enable.hint": 'разрешить это действие на кнопках',
    "access.action.disable.hint": 'запретить везде',
    "access.action.toggle_dangerous.hint": 'спрашивать подтверждение перед выполнением',
    "access.action.member.hint": 'кто может ставить действие на кнопку: Member+ (так же Staff, Admin)',
    "access.action.use_member.hint": 'кто может нажимать: Member+ (так же Staff, Admin)',
    "design.edit.hint": 'поменять цвета и подписи бота',
    "design.preview.hint": 'посмотреть, как выглядит',
    "design.reset.hint": 'вернуть как было по умолчанию',
    "buttons.home.create.hint": 'новый набор кнопок',
    "buttons.home.saved.hint": 'открыть сохранённые наборы',
    "buttons.builder.add.hint": 'новая кнопка: текст, цвет, действие',
    "buttons.builder.rename.hint": 'название набора и кто его видит',
    "buttons.builder.done.hint": 'сохранить набор',
    "buttons.builder.clear.hint": 'убрать все кнопки',
    "buttons.actions.preview.hint": 'показать кнопки только тебе',
    "buttons.actions.publish.hint": 'отправить кнопки в канал',
    "buttons.actions.delete.hint": 'удалить набор (опубликованные кнопки перестанут работать)',
    "forms.start.create.hint": 'новая форма-анкета',
    "forms.start.saved.hint": 'открыть готовые формы',
    "forms.builder.basic.hint": 'название, описание, кто видит',
    "forms.builder.question.hint": 'добавить вопрос (до 5)',
    "forms.builder.routing.hint": 'куда приходят заявки, кто их проверяет и что после одобрения',
    "forms.builder.target.hint": 'роль, которую выдадут после одобрения',
    "forms.builder.remove_question.hint": 'убрать последний вопрос',
    "forms.builder.toggle_dm.hint": 'писать заявителю в ЛС о решении',
    "forms.builder.save.hint": 'сохранить форму',
    "forms.use.apply.hint": 'заполнить форму самой (проверка)',
    "forms.use.publish.hint": 'отправить в канал кнопку «Подать заявку»',
    "forms.use.delete.hint": 'удалить форму',
    "templates.home.list.hint": 'все доступные тебе шаблоны',
    "templates.home.save.hint": 'сохранить шаблон из JSON',
    "templates.card.use.hint": 'отправить сообщение по шаблону',
    "templates.card.to_editor.hint": 'открыть в /embed и доработать',
    "templates.card.favorite.hint": 'добавить в избранное (только для тебя)',
    "templates.card.delete.hint": 'удалить шаблон',
    "webhooks.home.create.hint": 'новый вебхук в канале',
    "webhooks.home.list.hint": 'твои вебхуки',
    "webhooks.home.history.hint": 'что и когда отправлялось',
    "webhooks.card.show.hint": 'показать секретную ссылку (только тебе)',
    "webhooks.card.send.hint": 'написать сообщение от имени вебхука',
    "webhooks.card.rename.hint": 'сменить имя',
    "webhooks.card.avatar.hint": 'сменить аватарку',
    "webhooks.card.test.hint": 'отправить тестовое сообщение',
    "webhooks.card.history.hint": 'что отправлялось через этот вебхук',
    "webhooks.card.delete.hint": 'удалить вебхук',
    "webhooks.card.regenerate.hint": 'сделать новую ссылку, если старая утекла',
    "select.home.create_menu.hint": 'новое меню: роли и подсказка',
    "select.home.menus.hint": 'открыть созданные меню',
    "select.menu_actions.publish.hint": 'отправить меню в канал',
    "select.menu_actions.delete.hint": 'удалить меню',
    "logo.styles.create.hint": 'новый стиль иконок: название и описание',
    "logo.style_actions.edit.hint": 'поменять описание, модель или LoRA',
    "logo.style_actions.make_default.hint": 'использовать этот стиль, если не выбран другой',
    "logo.style_actions.describe.hint": 'бот сам опишет стиль по твоим референсам',
    "logo.style_actions.dataset.hint": 'архив для обучения LoRA — для точного попадания в стиль',
    "logo.style_actions.delete.hint": 'удалить стиль',
    "embed.home.create.hint": 'собрать новое сообщение с нуля',
    "embed.home.saved.hint": 'открыть сохранённые сообщения',
    "embed.home.from_message.hint": 'взять за основу уже отправленное сообщение (по ссылке)',
    "embed.home.use_template.hint": 'начать с готового шаблона',
    "embed.visibility.public.hint": 'все видят его в списках',
    "embed.visibility.private.hint": 'в списках видишь только ты (и админы)',
    "embed.visibility.restricted.hint": 'только выбранные роли или уровни',
    "embed.restriction.by_level.hint": 'например, только staff',
    "embed.restriction.by_role.hint": 'только у кого есть выбранные роли',
    "embed.editor.basic.hint": 'заголовок, текст, ссылка и цвет',
    "embed.editor.media.hint": 'маленькая картинка справа и большая снизу',
    "embed.editor.author_footer.hint": 'строка сверху (автор) и снизу (подпись)',
    "embed.editor.add_field.hint": 'блок «название — значение»; править — через список под кнопками',
    "embed.editor.visibility.hint": 'кто видит сообщение в списках',
    "embed.editor.meta.hint": "название для списка и обычный текст над embed'ом",
    "embed.editor.timestamp.hint": 'показать время отправки внизу',
    "embed.editor.delete_embed.hint": 'удалить этот embed',
    "embed.editor.confirm.hint": 'дальше — кнопки и сохранение',
    "embed.interactive.buttons.hint": 'добавить кнопки (до 20)',
    "embed.interactive.list.hint": 'выпадающий список с вариантами',
    "embed.interactive.native.hint": 'список ролей, людей или каналов из Discord',
    "embed.interactive.form.hint": 'кнопка «Подать заявку» для формы',
    "embed.interactive.send_now.hint": 'отправить в каналы; сохранить ли в список — спрошу после',
    "embed.interactive.save.hint": 'сохранить без отправки (например, чтобы прикрепить к кнопке)',
    "embed.save_after.save.hint": 'добавить в «Мои сохранённые» с названием',
    "embed.save_after.skip.hint": 'не засорять список: сообщение и так работает',
    "embed.interactive.clear_interactive.hint": 'убрать список',
    "embed.list.add_option.hint": 'новый вариант и что он делает',
    "embed.list.remove_last.hint": 'убрать последний (любой — через список)',
    "embed.list.done.hint": 'вернуться назад',
    "embed.native_select.role.hint": 'выбор роли',
    "embed.native_select.user.hint": 'выбор участника',
    "embed.native_select.channel.hint": 'выбор канала',
    "embed.native_select.mentionable.hint": 'роль или участник',
    "embed.buttons.add.hint": 'новая кнопка: текст, цвет, действие',
    "embed.buttons.remove_last.hint": 'убрать последнюю (любую — через список)',
    "embed.buttons.done.hint": 'вернуться назад',
    "embed.final.preview.hint": 'посмотреть, как сообщение будет выглядеть',
    "embed.final.send.hint": 'отправить в каналы, ветки или форум',
    "embed.final.edit.hint": 'изменить текст, картинки, кнопки',
    "embed.final.resync.hint": 'применить изменения к уже отправленным копиям',
    "embed.final.save_template_button.hint": 'сохранить как шаблон для повторного использования',
    "embed.final.export_json.hint": 'файл, чтобы перенести на другой сервер',
    "embed.final.history.hint": 'прошлые версии и откат',
    "embed.final.schedule.hint": 'отправлять автоматически в нужное время',
    "embed.final.triggers.hint": 'отправлять само, когда что-то случилось',
    "embed.final.settings.hint": 'автообновление, общий стиль, разное содержимое для ролей',
    "embed.final.delete.hint": 'удалить сообщение из бота',
    "automation.schedules.add.hint": 'новое время отправки',
    "automation.schedule_item.toggle.hint": 'приостановить или включить снова',
    "automation.schedule_item.remove.hint": 'удалить это расписание',
    "automation.triggers.member_join.hint": 'приветствие, когда кто-то заходит на сервер',
    "automation.triggers.thread_create.hint": 'ответ в каждую новую ветку или пост форума',
    "automation.triggers.keyword.hint": 'ответ, когда кто-то пишет нужное слово',
    "automation.keyword_scope.here.hint": 'слушать только канал, где открыта эта панель',
    "automation.keyword_scope.everywhere.hint": 'слушать все каналы',
    "automation.trigger_item.toggle.hint": 'приостановить или включить снова',
    "automation.trigger_item.remove.hint": 'удалить этот триггер',
    "automation.settings.live_timer.hint": 'переписывать отправленные сообщения каждые N минут',
    "automation.settings.parent.hint": 'брать цвет и оформление у другого сообщения',
    "automation.settings.add_variant.hint": 'показывать другим ролям другое сообщение',
    "automation.settings.clear_variants.hint": 'убрать все варианты',
    "automation.variant.staff.hint": 'вариант для модераторов и выше',
    "automation.variant.admin.hint": 'вариант для админов',
    "build_tools.version.preview.hint": 'как выглядела эта версия',
    "build_tools.version.restore.hint": 'вернуть эту версию (текущая сохранится в истории)',
}


def kind(key):
    """Тип значения для редактора: color / image / text."""
    if key.endswith("color"):
        return "color"
    if key.endswith("thumbnail") or key.startswith(("thumbnail.", "banner.")):
        return "image"
    return "text"
